project:
  type: website

website:
  title: "Projetos Kaizen usando R"
  navbar:
    right:
      - about.qmd
      - icon: youtube
        href: https://youtube.com/carvalhoribeiro
      - icon: github
        href: https://github.com/factorialmap
format:
  html:
    theme: Flatly
    css: styles.css

editor: visual

