project:
  type: website

website:
  title: "Carvalho Ribeiro Blog"
  site-url: https://carvalhoribeiro.netlify.app/
  description: "projetos kaizen"
  navbar:
    right:
      - text: Info
        href: about.qmd
      - icon: youtube
        href: https://youtube.com/carvalhoribeiro
      - icon: github
        href: https://github.com/factorialmap
format:
  html:
    theme: 
      light: Flatly
      dark: Darkly
    css: styles.css
    
    
editor: visual

