{
  "hash": "10c7b2182881a3ab18ea29f39620b12f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modelagem de Equações Estruturais\"\nsubtitle: \"Conceitos e práticas de structural equation modeling SEM usando R\"\nauthor: \"Marcelo Carvalho dos Anjos\"\ndate: \"2025-08-22\"\ncategories: [Modelos]\nformat: html\nbibliography: references.bib\n---\n\n\n\n### {{< fa 1 >}} [**O que é a SEM**]{style=\"color: #5AC8BE ;\"}\n\n-   **Em linguagem simples por exemplo no contexto da manufatura e melhoria de processos**: o SEM é uma ferramenta estatística que ajuda a entender como diferents fatores dentro de um processo estão conectados permitindo analisar várias causas e efeitos ao mesmo tempo, mesmo quando alguns desses fatores não são diretamente medidos(e.g. clima organizacional, engajamento dos operadores, motivação etc).\n\n-   **Ponto de vista técnico**: É uma técnica estatística multivariada que permite testar e estimar relações complexas entre variáveis observadas (dados coletados) e variáveis latentes (conceitos não diretamente mensuráveis, como inteligência ou satisfação). Ela combina elementos de análise fatorial e regressão múltipla em um único modelo.\n\n**Importante** Ela trabalha com dois tipos de variáveis.\n\n-   **Variáveis observadas**: Ajudam a controlar e monitorar o processo. São coisas que conseguimos medir diretamente no chão da fábrica(e.g. temperatura de uma maquina, tempo de produção de uma peça, número de peças com defeito, peso de um produto, horas de treinamento recebidos). Estas variáveis vêm de sensores, relatórios ou medições feitas por pessoas. Elas são vistas e registradas.\n\n-   **Variáveis latentes**: Ajudam a entender o que está por trás dos resultados e melhorar o sistema de forma mais profunda. São coisas que não conseguimos medir diretamente, mas que influenciam o processo. É necessário usar outras variáveis para estimar ou representá-las(e.g. motivação dos operadores, qualidade do ambiente de trabalho, engajamento com segurança, cultura de melhoria contínua, satisfação com treinamento). Não há um sensor que mede a motivação por exemplo, mas pode-se utilizar de perguntas de uma pesquisa ou observar o comportamentos para representar esse conceito.\n\nPS. Há conteúdos no Youtube de excelente qualidade que ajudam a compreender melhor esses modelos e suas aplicações como por exemplo, o do professor @prof.diogeness.bido2021\n\n### {{< fa 2 >}} [**Qual o objetivo?**]{style=\"color: #5AC8BE ;\"}\n\n-   Identificar relações ocultas entre variáveis de processo, qualidade, produtividade e comportamento humano.\n-   Melhorar decisões com base em dados, não só em intuição.\n-   Validar hipóteses sobre o que realmente afeta o desempenho(e.g. em uma linha de produção, satisfação dos consumidores).\n-   Modelar relações causais entre variáveis.\n-   Testar teorias que envolvem múltiplas dependências simultâneas.\n-   Validar construtos teóricos por meio de dados empíricos.\n-   Avaliar a qualidade de modelos estatísticos complexos.\n\n### {{< fa 3 >}} [**De onde vem?**]{style=\"color: #5AC8BE ;\"}\n\nNa academia, o SEM surgiu para estudar fenômenos complexos como comportamento humano, educação e psicologia onde foi desenvolvido a partir da evolução da análise fatorial e da path analysis (análise de caminhos), ganhando força nas ciências sociais, psicologia, marketing e educação.\n\nA necessidade surgiu da limitação de métodos estatísticos tradicionais (como regressão simples ou múltipla) que não conseguiam: - Capturar relações simultâneas entre múltiplas variáveis. - Trabalhar com variáveis latentes (não diretamente mensuráveis). - Testar modelos teóricos complexos com múltiplas etapas e dependências.\n\nNa industria onde há sistemas igualmente complexos como uma fábrica com centenas de variáveis interagindo. Ela surge como ferramenta complementar a métodos tradicionais(e.g. gráficos de controle, regressão simples etc) os quais podem não conseguir capturar todas as complexidades existentes no processo. O SEM entra como uma solução para modelar sistemas industriais de forma mais completa.\n\n### {{< fa 4 >}} [**Como fazer?**]{style=\"color: #5AC8BE ;\"}\n\n**Caso1 - Apenas para trazer sentido para nosso exemplo usando mtcars dataset**\n\nIremos fazer um modelo sem variáveis latentes, chamado também de `path analysis` apenas para ilustrar de forma simples o problema e a solução.\n\n1.  A especificação do modelo SEM é feito com uma string(em formato de texto), note que foi usado aspas indicado que o formato é texto.\n\n2.  Há duas equações estruturais sendo:\n\n-   **mpg \\~ cyl + disp + hp**: o consumo de combustível (mpg) é explicado por número de cilindros (cyl), deslocamento (disp) e potência (hp).\n-   **qsec \\~ disp + hp + wt**: o tempo de aceleração (qsec) é explicado por deslocamento (disp), potência (hp) e peso (wt).\n\n3.  Implementar via software usando R/RStudio @rstudio/2025, Lavaan package @rosseel2024, Quarto Publishing @quarto2025\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# packages\nlibrary(tidyverse)\nlibrary(lavaan)\nlibrary(lavaanPlot)\n\n# step1: especificação do modelo SEM\nmdl_spec_sem_mtcas <- \"\nmpg ~ cyl + disp + hp\nqsec ~ disp + hp + wt\n\"\n\n# step2: rodar o modelo\nmdl_fit_sem_mtcars <- sem(mdl_spec_sem_mtcas, data = mtcars)\n\n# step3: checar resultados\nsummary(mdl_fit_sem_mtcars, fit.measures = TRUE, standardized = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-19 ended normally after 32 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                         9\n\n  Number of observations                            32\n\nModel Test User Model:\n                                                      \n  Test statistic                                18.266\n  Degrees of freedom                                 2\n  P-value (Chi-square)                           0.000\n\nModel Test Baseline Model:\n\n  Test statistic                               101.965\n  Degrees of freedom                                 9\n  P-value                                        0.000\n\nUser Model versus Baseline Model:\n\n  Comparative Fit Index (CFI)                    0.825\n  Tucker-Lewis Index (TLI)                       0.213\n\nLoglikelihood and Information Criteria:\n\n  Loglikelihood user model (H0)               -124.003\n  Loglikelihood unrestricted model (H1)       -114.870\n                                                      \n  Akaike (AIC)                                 266.005\n  Bayesian (BIC)                               279.197\n  Sample-size adjusted Bayesian (SABIC)        251.140\n\nRoot Mean Square Error of Approximation:\n\n  RMSEA                                          0.504\n  90 Percent confidence interval - lower         0.309\n  90 Percent confidence interval - upper         0.727\n  P-value H_0: RMSEA <= 0.050                    0.000\n  P-value H_0: RMSEA >= 0.080                    1.000\n\nStandardized Root Mean Square Residual:\n\n  SRMR                                           0.041\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nRegressions:\n                   Estimate   Std.Err  z-value  P(>|z|)   Std.lv   Std.all\n  mpg ~                                                                   \n    cyl               -0.987    0.738   -1.337    0.181    -0.987   -0.293\n    disp              -0.021    0.010   -2.178    0.029    -0.021   -0.435\n    hp                -0.017    0.014   -1.218    0.223    -0.017   -0.190\n  qsec ~                                                                  \n    disp              -0.008    0.004   -2.122    0.034    -0.008   -0.559\n    hp                -0.023    0.004   -5.229    0.000    -0.023   -0.849\n    wt                 1.695    0.398    4.256    0.000     1.695    0.908\n\nCovariances:\n                   Estimate   Std.Err  z-value  P(>|z|)   Std.lv   Std.all\n .mpg ~~                                                                  \n   .qsec               0.447    0.511    0.874    0.382     0.447    0.156\n\nVariances:\n                   Estimate   Std.Err  z-value  P(>|z|)   Std.lv   Std.all\n   .mpg                8.194    2.049    4.000    0.000     8.194    0.234\n   .qsec               0.996    0.249    4.000    0.000     0.996    0.308\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-tip collapse=\"true\"}\n## Clique aqui para mais detalhes sobre a interpretação dos resultados do modelo\n\n**Interpretação da Saída:**\n\n**1. Informações Básicas do Modelo:**\n\n-   **`lavaan 0.6-19 ended normally after 32 iterations`**: O processo de estimação do modelo convergiu com sucesso após 32 iterações. Isso é bom, indica que o algoritmo encontrou uma solução estável.\n-   **`Estimator ML`**: O estimador usado foi o de Máxima Verossimilhança (Maximum Likelihood). Este é o estimador padrão e mais comum para SEM quando os dados são aproximadamente normais.\n-   **`Optimization method NLMINB`**: O método de otimização usado.\n-   **`Number of model parameters 9`**: Seu modelo possui 9 parâmetros que foram estimados (por exemplo, os coeficientes de caminho, variâncias residuais, covariâncias).\n-   **`Number of observations 32`**: Você está usando um conjunto de dados com 32 observações (linhas), que é o tamanho do conjunto de dados `mtcars`.\n\n**2. Teste do Modelo do Usuário (`Model Test User Model`):**\n\nEste é o teste de qui-quadrado (Chi-square test) do seu modelo. A hipótese nula ($H_0$) deste teste é que o seu modelo se ajusta *perfeitamente* aos dados da população. Uma hipótese alternativa ($H_1$) é que o modelo não se ajusta perfeitamente.\n\n-   **`Test statistic 18.266`**: O valor do teste de qui-quadrado.\n\n-   **`Degrees of freedom 2`**: Os graus de liberdade do seu modelo.\n\n-   **`P-value (Chi-square) 0.000`**: O p-valor associado.\n\n    **Interpretação:** Como o p-valor (0.000) é menor que 0.05 (ou qualquer nível de significância usual), nós **rejeitamos a hipótese nula**. Isso significa que o seu modelo (o \"modelo do usuário\") *não* se ajusta perfeitamente aos dados observados.\n\n    **Cuidado:** Embora isso possa parecer uma má notícia, o teste de qui-quadrado é muito sensível, especialmente com tamanhos de amostra maiores. Com 32 observações, a rejeição aqui é um sinal de que o modelo não é *perfeito*. No entanto, em SEM, raramente esperamos um ajuste perfeito. O foco geralmente é em ter um \"bom ajuste\" ou um \"ajuste razoável\", avaliado por outros índices de ajuste.\n\n**3. Teste do Modelo de Linha de Base (`Model Test Baseline Model`):**\n\nO modelo de linha de base (baseline model) é um modelo nulo onde todas as variáveis são consideradas não correlacionadas. Serve como um ponto de comparação para o seu modelo.\n\n-   **`Test statistic 101.965`**\n\n-   **`Degrees of freedom 9`**\n\n-   **`P-value 0.000`**\n\n    **Interpretação:** O modelo de linha de base também não se ajusta bem aos dados (p-valor \\< 0.05), o que é esperado, pois é um modelo muito restritivo. Este teste é usado principalmente para calcular os índices de ajuste comparativos (CFI, TLI).\n\n**4. Modelo do Usuário versus Modelo de Linha de Base (`User Model versus Baseline Model`):**\n\nEsses são índices de ajuste incrementais, que comparam o seu modelo com o modelo de linha de base.\n\n-   **`Comparative Fit Index (CFI) 0.825`**:\n\n    -   **Interpretação:** O CFI varia de 0 a 1. Valores acima de 0.90 ou 0.95 são geralmente considerados indicativos de um bom ajuste. Seu CFI de 0.825 está abaixo dos critérios comuns para um bom ajuste (geralmente \\> 0.90 ou \\> 0.95). Isso sugere que o seu modelo não melhora substancialmente o ajuste em comparação com o modelo nulo o suficiente para ser considerado um \"bom\" ajuste.\n\n-   **`Tucker-Lewis Index (TLI) 0.213`**:\n\n    -   **Interpretação:** O TLI (também conhecido como NNFI) é outro índice incremental, também variando geralmente de 0 a 1, com valores \\> 0.90 ou \\> 0.95 indicando bom ajuste. Seu TLI de 0.213 é **muito baixo**, indicando um ajuste pobre do modelo.\n\n    **Em resumo para CFI e TLI:** Ambos os índices sugerem que o seu modelo não está bem ajustado aos dados.\n\n**5. Critérios de Log-Verossimilhança e Informação (`Loglikelihood and Information Criteria`):**\n\nEsses critérios são usados para comparar modelos, favorecendo modelos com melhor ajuste e menor complexidade. Valores menores são geralmente preferíveis.\n\n-   **`Loglikelihood user model (H0) -124.003`**: A log-verossimilhança do seu modelo.\n\n-   **`Loglikelihood unrestricted model (H1) -114.870`**: A log-verossimilhança do modelo não restrito (também conhecido como modelo saturado), que é o modelo com o melhor ajuste possível aos dados.\n\n-   **`Akaike (AIC) 266.005`**: Critério de Informação de Akaike.\n\n-   **`Bayesian (BIC) 279.197`**: Critério de Informação Bayesiano.\n\n-   **`Sample-size adjusted Bayesian (SABIC) 251.140`**: BIC ajustado para o tamanho da amostra.\n\n    **Interpretação:** Esses valores são mais úteis para comparar seu modelo com modelos alternativos (modelos aninhados ou não aninhados). Modelos com valores menores de AIC, BIC e SABIC são considerados melhores. Isoladamente, eles não indicam \"bom\" ou \"mau\" ajuste.\n\n**6. Erro Quadrático Médio da Aproximação (`Root Mean Square Error of Approximation` - RMSEA):**\n\nO RMSEA é um índice de ajuste absoluto que mede o quão mal o modelo se ajusta aos dados. Valores menores indicam melhor ajuste.\n\n-   **`RMSEA 0.504`**:\n    -   **Interpretação:** Um RMSEA \\< 0.05 é considerado um bom ajuste, entre 0.05 e 0.08 é um ajuste razoável, e \\> 0.10 é um ajuste pobre. Seu valor de 0.504 é **extremamente alto**, indicando um ajuste muito ruim do modelo aos dados.\n-   **`90 Percent confidence interval - lower 0.309`**\n-   **`90 Percent confidence interval - upper 0.727`**: O intervalo de confiança para o RMSEA é muito amplo e totalmente acima de 0.08, reforçando o mau ajuste.\n-   **`P-value H_0: RMSEA <= 0.050 0.000`**: Este é o p-valor para o teste da hipótese nula de que o RMSEA é menor ou igual a 0.05. Como é 0.000, rejeitamos essa hipótese.\n-   **`P-value H_0: RMSEA >= 0.080 1.000`**: Este é o p-valor para o teste da hipótese nula de que o RMSEA é maior ou igual a 0.08. Como é 1.000, não podemos rejeitar essa hipótese, o que significa que é muito provável que seu RMSEA seja realmente \\>= 0.08.\n\n**Em resumo para RMSEA:** O RMSEA confirma que o modelo tem um ajuste muito pobre aos dados.\n\n------------------------------------------------------------------------\n\n**Tabela de Regressão**\n\nÉ a parte mais importante da saída para entender as relações específicas do modelo SEM. Ela detalha os coeficientes estimados para cada caminho (regressão), covariância e variância\\*\\*\n\n------------------------------------------------------------------------\n\n**1. Informações sobre Erros Padrão (`Standard errors`):**\n\n-   **`Standard errors Standard`**: Indica que os erros padrão foram calculados usando o método padrão (não robusto).\n\n-   **`Information Expected`**: O tipo de matriz de informação utilizada na estimação (esperada).\n\n-   **`Information saturated (h1) model Structured`**: Refere-se a como a matriz de informação é tratada para o modelo saturado (h1).\n\n    **Interpretação:** Essas são informações técnicas sobre como os erros padrão e os testes de significância foram calculados. Geralmente, você não precisa se aprofundar muito nisso, a menos que haja problemas de convergência ou preocupações com a normalidade dos dados.\n\n**2. Regressões (`Regressions`):**\n\nEsta seção mostra os efeitos diretos (caminhos) de uma variável sobre outra, semelhantes aos coeficientes de regressão.\n\n-   **`Estimate`**: O coeficiente de regressão não padronizado. Representa a mudança na variável dependente para cada unidade de mudança na variável preditora, mantendo as outras preditoras constantes.\n-   **`Std.Err`**: O erro padrão do coeficiente estimado.\n-   **`z-value`**: O valor Z do teste de Wald, que é o `Estimate` dividido pelo `Std.Err`. É usado para testar a significância estatística do coeficiente.\n-   **`P(>|z|)`**: O p-valor associado ao valor Z. Se for menor que seu nível de significância (geralmente 0.05), o coeficiente é considerado estatisticamente significativo.\n-   **`Std.lv`**: Coeficientes padronizados com base apenas nas variáveis latentes (se houver). Neste modelo, como você só tem variáveis observadas, será o mesmo que `Estimate`.\n-   **`Std.all`**: Coeficientes padronizados com base em todas as variáveis (observadas e latentes). Estes são os que você vê no diagrama e são os mais úteis para comparar a força relativa dos efeitos. Eles variam de -1 a 1.\n\n**Detalhes da Interpretação:**\n\n**a) `mpg ~ cyl` (mpg é predito por cyl):** \\* `Estimate = -0.987`: Para cada aumento de 1 cilindro, o `mpg` diminui em 0.987 unidades. \\* `P(>|z|) = 0.181`: Não é significativo (p \\> 0.05). Isso significa que o número de cilindros não tem um efeito direto estatisticamente significativo sobre `mpg` APÓS contabilizar as outras variáveis no modelo para `mpg`. \\* `Std.all = -0.293`: Um efeito padronizado fraco a moderado, mas não significativo. (Corresponde a `-0.29` no diagrama).\n\n**b) `mpg ~ disp` (mpg é predito por disp):** \\* `Estimate = -0.021`: Para cada aumento de 1 unidade em `disp`, o `mpg` diminui em 0.021 unidades. \\* `P(>|z|) = 0.029`: **Significativo** (p \\< 0.05). `disp` tem um efeito direto negativo estatisticamente significativo sobre `mpg`. \\* `Std.all = -0.435`: Um efeito padronizado moderado e significativo. (Corresponde a `-0.44` no diagrama).\n\n**c) `mpg ~ hp` (mpg é predito por hp):** \\* `Estimate = -0.017`: Para cada aumento de 1 unidade em `hp`, o `mpg` diminui em 0.017 unidades. \\* `P(>|z|) = 0.223`: Não é significativo (p \\> 0.05). `hp` não tem um efeito direto estatisticamente significativo sobre `mpg` APÓS contabilizar as outras variáveis. \\* `Std.all = -0.190`: Um efeito padronizado fraco e não significativo. (Corresponde a `-0.19` no diagrama).\n\n**d) `qsec ~ disp` (qsec é predito por disp):** \\* `Estimate = -0.008`: Para cada aumento de 1 unidade em `disp`, o `qsec` diminui em 0.008 unidades. \\* `P(>|z|) = 0.034`: **Significativo** (p \\< 0.05). `disp` tem um efeito direto negativo estatisticamente significativo sobre `qsec`. \\* `Std.all = -0.559`: Um efeito padronizado forte e significativo. (Corresponde a `-0.56` no diagrama).\n\n**e) `qsec ~ hp` (qsec é predito por hp):** \\* `Estimate = -0.023`: Para cada aumento de 1 unidade em `hp`, o `qsec` diminui em 0.023 unidades. \\* `P(>|z|) = 0.000`: **Altamente significativo** (p \\< 0.001). `hp` tem um efeito direto negativo muito forte e estatisticamente significativo sobre `qsec`. \\* `Std.all = -0.849`: Um efeito padronizado muito forte e significativo. (Corresponde a `-0.85` no diagrama).\n\n**f) `qsec ~ wt` (qsec é predito por wt):** \\* `Estimate = 1.695`: Para cada aumento de 1 unidade em `wt`, o `qsec` aumenta em 1.695 unidades. \\* `P(>|z|) = 0.000`: **Altamente significativo** (p \\< 0.001). `wt` tem um efeito direto positivo muito forte e estatisticamente significativo sobre `qsec`. \\* `Std.all = 0.908`: Um efeito padronizado muito forte e significativo. (Corresponde a `0.91` no diagrama).\n\n**Resumo das Regressões:** \\* Para `mpg`, apenas `disp` tem um efeito direto significativo (e negativo). \\* Para `qsec`, `disp`, `hp` e `wt` têm efeitos diretos significativos. `hp` (negativo) e `wt` (positivo) são os preditores mais fortes de `qsec`.\n\n**3. Covariâncias (`Covariances`):**\n\nEsta seção mostra as covariâncias estimadas entre variáveis que não têm uma relação causal direta modelada (ou entre os resíduos das variáveis endógenas).\n\n-   **`.mpg ~~ .qsec` (Covariância entre os resíduos de mpg e qsec):**\n\n    -   `Estimate = 0.447`: A covariância não padronizada dos resíduos.\n    -   `P(>|z|) = 0.382`: Não é significativo (p \\> 0.05).\n    -   `Std.all = 0.156`: Uma correlação residual padronizada fraca e não significativa. (Corresponde a `0.16` no diagrama, que é a correlação entre os resíduos, não as variáveis brutas).\n\n    **Interpretação:** A covariância (ou correlação) entre os resíduos de `mpg` e `qsec` não é estatisticamente significativa. Isso significa que, após contabilizar os efeitos das variáveis preditoras (`cyl`, `disp`, `hp` para `mpg`; `disp`, `hp`, `wt` para `qsec`), qualquer variância restante em `mpg` e `qsec` não está significativamente relacionada entre si.\n\n**4. Variâncias (`Variances`):**\n\nEsta seção mostra as variâncias estimadas para as variáveis exógenas e as variâncias residuais para as variáveis endógenas.\n\n-   **`.mpg` (Variância residual de mpg):**\n\n    -   `Estimate = 8.194`: A variância não padronizada do resíduo de `mpg`.\n    -   `P(>|z|) = 0.000`: Altamente significativo, o que é esperado para variâncias.\n    -   `Std.all = 0.234`: A variância residual padronizada (1 - R-quadrado). Isso significa que 23.4% da variância de `mpg` não é explicada pelas preditoras no modelo. Consequentemente, as preditoras (`cyl`, `disp`, `hp`) explicam `1 - 0.234 = 0.766` ou 76.6% da variância em `mpg` (R-quadrado para `mpg`). (Corresponde a `0.23` no diagrama).\n\n-   **`.qsec` (Variância residual de qsec):**\n\n    -   `Estimate = 0.996`: A variância não padronizada do resíduo de `qsec`.\n    -   `P(>|z|) = 0.000`: Altamente significativo.\n    -   `Std.all = 0.308`: A variância residual padronizada (1 - R-quadrado). Isso significa que 30.8% da variância de `qsec` não é explicada pelas preditoras no modelo. Consequentemente, as preditoras (`disp`, `hp`, `wt`) explicam `1 - 0.308 = 0.692` ou 69.2% da variância em `qsec` (R-quadrado para `qsec`). (Corresponde a `0.31` no diagrama).\n\n    **Interpretação:** As variâncias residuais indicam a proporção da variância das variáveis dependentes que *não* é explicada pelo modelo. Os valores padronizados (`Std.all`) fornecem o complementar do R-quadrado. Seu modelo explica uma proporção razoável da variância em ambas as variáveis dependentes.\n\n**Considerações Finais:**\n\nLembre-se da interpretação anterior sobre o ajuste geral do modelo. Embora alguns caminhos individuais sejam estatisticamente significativos e os Rs-quadrados sejam razoáveis, os índices de ajuste globais (CFI, TLI, RMSEA) indicaram que o modelo como um todo não se ajusta bem aos dados. Isso significa que, embora as relações específicas que você encontrou sejam interessantes, a estrutura geral do seu modelo pode não ser a melhor representação dos dados, possivelmente devido ao pequeno tamanho da amostra ou a um modelo teórico incompleto/incorreto.\n\nEm resumo, seu modelo atual não se ajusta bem aos dados. A primeira etapa é sempre revisar a teoria por trás do seu modelo e a especificação no `lavaan`. Dada a pequena amostra do `mtcars`, é desafiador construir um modelo SEM robusto com este conjunto de dados.\n\n**Conclusão Geral e Recomendações:**\n\nCom base em todos os índices de ajuste (Chi-quadrado, CFI, TLI, RMSEA), seu modelo atual apresenta um **ajuste muito pobre** aos dados do `mtcars`. Isso significa que as relações e a estrutura que você hipotetizou no seu diagrama (e que o `lavaan` tentou ajustar) não representam bem as covariâncias observadas no seu conjunto de dados.\n\n**O que fazer a seguir?**\n\n1.  **Revisar o Modelo Teórico:**\n    -   Seu modelo SEM deve ser baseado em teoria. As relações que você desenhou fazem sentido conceitualmente?\n    -   Há alguma variável importante faltando no modelo que poderia explicar melhor `mpg` ou `qsec`?\n    -   Você incluiu todas as covariâncias entre as variáveis exógenas (`cyl`, `disp`, `hp`, `wt`) que são esperadas? (Pelo diagrama, parece que sim, mas verifique se o modelo `lavaan` as especificou corretamente).\n2.  **Verificar Especificação do Modelo:**\n    -   Certifique-se de que a sintaxe do `lavaan` reflete *exatamente* o diagrama que você pretendia testar. Às vezes, pequenos erros de digitação ou omissões podem levar a um ajuste ruim.\n    -   Se você usou um atalho como `x ~~ y` para covariância ou `y ~ x` para regressão, confira se não há setas ou covariâncias que deveriam estar lá, mas não foram especificadas.\n3.  **Explorar Modificações (Com Cuidado):**\n    -   O `lavaan` pode fornecer índices de modificação (`modindices()`) que sugerem quais parâmetros (caminhos ou covariâncias) poderiam ser adicionados ao modelo para melhorar o ajuste.\n    -   **Importante:** Use índices de modificação com **muita cautela** e apenas se as modificações fizerem sentido teórico. Fazer mudanças apenas para melhorar o ajuste sem base teórica pode levar a um modelo superajustado aos dados da amostra e que não generaliza bem.\n4.  **Tamanho da Amostra:**\n    -   Com 32 observações, você tem um tamanho de amostra muito pequeno para SEM. Modelos SEM geralmente exigem amostras maiores (centenas de observações) para ter poder estatístico adequado e para que os índices de ajuste funcionem de forma confiável. Um tamanho de amostra pequeno pode inflar o qui-quadrado e dificultar a obtenção de um bom ajuste, mesmo que o modelo seja teoricamente correto. No caso do `mtcars`, que tem apenas 32 carros, as limitações do conjunto de dados são um fator importante.\n5.  **Multicolinearidade:**\n    -   No diagrama, vimos correlações muito altas entre `cyl`, `disp`, `hp`, `wt`. Embora SEM possa lidar com isso melhor do que regressão múltipla tradicional, correlações extremamente altas ainda podem dificultar a estimação ou interpretação dos efeitos diretos.\n\n**Conexão com o Diagrama abaixo**\n\nOs valores na coluna `Std.all` correspondem diretamente aos números exibidos nas setas do seu diagrama (`semPlot`). A espessura das setas no diagrama visualmente representa a magnitude desses `Std.all`. A cor (verde/vermelho) reflete o sinal do `Estimate` (positivo/negativo).\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\nAgora, vamos plotar os resultados no diagrama usando o pacote `semPlot` @epskamp2025\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(semPlot)\n\n# Gerar o diagrama de caminhos\nsemPaths(mdl_fit_sem_mtcars, \n         what = \"std\",         # mostra coeficientes padronizados\n         layout = \"tree\",      # organiza em formato de árvore\n         edge.label.cex = 1.2, # tamanho dos rótulos\n         sizeMan = 8,          # tamanho dos nós\n         sizeLat = 10,         # tamanho das variáveis latentes(não tem nesse modelo)\n         nCharNodes = 0)  \n```\n\n::: {.cell-output-display}\n![](modelagem_equacoes_estruturais_files/figure-html/semplot_mtcars-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n::: {.callout-tip collapse=\"true\"}\n## Clique aqui pra expandir se precisar da interpretação do gráfico\n\nO diagrama de caminho (path diagram) acima, representa as relações hipotéticas entre variáveis usando o conjunto de dados `mtcars`.\n\n**Visão Geral do Diagrama:**\n\n-   **Variáveis Observadas (Retângulos):** representa uma variável observada do conjunto de dados `mtcars`(e.g cyl(número de cilindros), disp(cilindrada),hp(potência),wt(peso do veículo), mpg(milhas por galão), qsec(tempo de 1/4 de milha).\n\n-   **Setas e Linhas:** representam relações causais ou diretivas (regressões), enquanto as linhas bidirecionais curvas representam covariâncias ou correlações.\n\n-   **Cores:** Verde indica uma relação positiva, enquanto a vermelha, relação negativa.\n\n-   **Espessura da Linha/Seta:** É proporcional à magnitude do coeficiente de caminho (seja ele um coeficiente de regressão ou uma correlação). Linhas mais grossas indicam relações mais fortes.\n\n-   **Números nas Setas/Linhas:** são os coeficientes de caminho padronizados (standardized path coefficients), que são análogos a coeficientes de regressão padronizados ou correlações. Eles variam de -1 a 1. Onde valores próximos a 0 indicam relações fracas e valores próximos a 1 (ou -1) indicam relações fortes.\n\n**Interpretação Detalhada por Seções:**\n\n**1. Relações entre as Variáveis de \"Características do Carro\" (Topo):**\n\n-   **Setas Bidirecionais Curvas na Parte Superior (entre cyl, disp, hp, wt):** Estas representam as correlações entre essas variáveis de características do carro. Todas são verdes e têm valores altos, indicando fortes correlações positivas.\n    -   `cyl <-> cyl` (1.00): Isso é o \"erro\" ou variância não explicada da própria variável. Em modelos SEM, geralmente é a variância residual ou a variância de um erro, mas para variáveis exógenas (sem setas apontando para elas), pode representar a variância total. No entanto, o `semPlot` pode desenhar isso como a variância total de uma variável quando não há preditores, ou a variância residual de uma variável endógena. Neste caso, para `cyl`, `disp`, `hp`, `wt` que parecem ser variáveis exógenas (ou seja, suas causas não são modeladas aqui, elas são as preditoras), esse `1.00` geralmente representa que 100% da variância delas é explicada por si mesmas no contexto de não serem preditas por outras variáveis no modelo, ou simplesmente sua variância total (que é 1 em uma escala padronizada).\n    -   `cyl <-> disp`: Correlação de 0.90 (forte, positiva). Carros com mais cilindros tendem a ter maior cilindrada.\n    -   `disp <-> hp`: Correlação de 0.83 (forte, positiva). Carros com maior cilindrada tendem a ter maior potência.\n    -   `disp <-> disp` (1.00): O mesmo que para `cyl`.\n    -   `hp <-> hp` (1.00): O mesmo.\n    -   `hp <-> wt`: Correlação de 0.79 (forte, positiva). Carros com maior potência tendem a ser mais pesados.\n    -   `disp <-> wt`: Correlação de 0.78 (forte, positiva). Carros com maior cilindrada tendem a ser mais pesados.\n    -   `wt <-> wt` (1.00): O mesmo.\n    -   `cyl <-> hp` (não mostrado diretamente, mas inferido através de disp).\n    -   `cyl <-> wt` (não mostrado diretamente, mas inferido).\n    -   `hp <-> cyl` (0.89): Forte correlação positiva.\n    -   `wt <-> hp` (0.66): Correlação positiva.\n    -   **Em resumo:** Essas quatro variáveis (`cyl`, `disp`, `hp`, `wt`) são altamente correlacionadas entre si. Isso é esperado, pois elas são características intrínsecas do motor e do carro que geralmente andam juntas.\n\n**2. Relações entre Variáveis de Características do Carro e `mpg` (Consumo):**\n\n-   `cyl -> mpg`: Coeficiente de -0.29 (vermelho, fraco a moderado, negativo). Carros com mais cilindros tendem a ter menor `mpg` (pior consumo de combustível).\n-   `disp -> mpg`: Coeficiente de -0.44 (vermelho, moderado, negativo). Carros com maior cilindrada tendem a ter menor `mpg`.\n-   `hp -> mpg`: Coeficiente de -0.19 (vermelho, fraco, negativo). Carros com maior potência tendem a ter menor `mpg`.\n-   `wt -> mpg`: **Não há seta direta de `wt` para `mpg` neste modelo.** Isso sugere que o modelo não assume uma relação direta de `wt` para `mpg` APÓS contabilizar as outras variáveis, ou a relação não foi estatisticamente significativa para ser incluída ou é indireta.\n    -   **Em resumo:** Cilindros, cilindrada e potência estão negativamente associadas ao consumo de combustível. Carros com características de motor mais \"potentes\" ou \"maiores\" tendem a consumir mais combustível (menor `mpg`). `disp` tem o efeito direto negativo mais forte em `mpg`.\n\n**3. Relações entre Variáveis de Características do Carro e `qsec` (Tempo de 1/4 de Milha):**\n\n-   `disp -> qsec`: Coeficiente de -0.56 (vermelho, moderado a forte, negativo). Carros com maior cilindrada tendem a ter um tempo de 1/4 de milha menor (ou seja, são mais rápidos).\n-   `hp -> qsec`: Coeficiente de -0.85 (vermelho, muito forte, negativo). Carros com maior potência tendem a ter um tempo de 1/4 de milha significativamente menor (são muito mais rápidos).\n-   `wt -> qsec`: Coeficiente de 0.91 (verde, muito forte, positivo). Carros mais pesados tendem a ter um tempo de 1/4 de milha maior (ou seja, são mais lentos).\n    -   **Em resumo:** Cilindrada e potência contribuem para um carro mais rápido (menor `qsec`), com a potência (`hp`) sendo o fator mais influente. O peso (`wt`), por outro lado, torna o carro mais lento (maior `qsec`), com uma influência igualmente forte.\n\n**4. Relação entre `mpg` e `qsec`:**\n\n-   `mpg <-> qsec`: Coeficiente de 0.16 (verde, fraco, positivo). Há uma correlação positiva fraca entre `mpg` e `qsec`. Carros com melhor consumo de combustível tendem a ter um tempo de 1/4 de milha ligeiramente maior (são um pouco mais lentos). É importante notar que esta é uma *correlação* bidirecional, não uma relação causal direta no sentido de `mpg` causando `qsec` ou vice-versa neste modelo específico. Pode ser que variáveis não modeladas ou efeitos indiretos expliquem essa correlação.\n\n**5. Variância Residual (Loops nas Variáveis Dependentes):**\n\n-   `mpg <-> mpg` (0.23): Este é o coeficiente de variância residual para `mpg`. Significa que 23% da variância de `mpg` NÃO é explicada pelas variáveis preditoras (`cyl`, `disp`, `hp`) incluídas no modelo para `mpg`. Ou, em outras palavras, as variáveis `cyl`, `disp`, `hp` explicam `1 - 0.23 = 0.77` ou 77% da variância em `mpg` (o R-quadrado).\n-   `qsec <-> qsec` (0.31): Este é o coeficiente de variância residual para `qsec`. Significa que 31% da variância de `qsec` NÃO é explicada pelas variáveis preditoras (`disp`, `hp`, `wt`) incluídas no modelo para `qsec`. Portanto, `disp`, `hp`, `wt` explicam `1 - 0.31 = 0.69` ou 69% da variância em `qsec`.\n\n**Conclusões Gerais e Interpretação do Modelo:**\n\nEste modelo tenta explicar o consumo de combustível (`mpg`) e o desempenho de 1/4 de milha (`qsec`) usando características do motor e peso do carro.\n\n-   **Consumo de Combustível (`mpg`):** É predominantemente influenciado negativamente por `disp` e `cyl`, e um pouco por `hp`. Carros com motores maiores/mais potentes tendem a ser menos eficientes em termos de combustível.\n-   **Desempenho de 1/4 de Milha (`qsec`):** É fortemente influenciado pela potência (`hp`) e peso (`wt`), e também pela cilindrada (`disp`). Mais potência e menor cilindrada (para motores mais eficientes) levam a carros mais rápidos, enquanto maior peso torna os carros mais lentos. `hp` e `wt` têm os efeitos mais proeminentes.\n-   **Correlações Elevadas entre Preditoras:** As altas correlações entre `cyl`, `disp`, `hp`, e `wt` são um ponto importante. Em modelos de regressão múltipla, isso poderia indicar multicolinearidade. Em SEM, isso é explicitamente modelado pelas covariâncias. Isso significa que essas variáveis não são independentes em seus efeitos, e os efeitos diretos que vemos (`cyl -> mpg`, `disp -> mpg`, etc.) são os efeitos *após* contabilizar a inter-relação entre as preditoras.\n-   **Poder Explicativo:** O modelo explica uma grande parte da variância em `mpg` (77%) e `qsec` (69%), o que é bastante razoável.\n\nEste diagrama oferece uma representação visual clara das relações entre as variáveis, permitindo entender rapidamente quais fatores são mais influentes e em que direção. As setas mais espessas e os coeficientes de maior magnitude (`-0.85` de `hp` para `qsec`, `0.91` de `wt` para `qsec`, `0.90` de `cyl` para `disp`) são os pontos-chave de atenção para as relações mais fortes.\n:::\n\n------------------------------------------------------------------------\n\n**Caso2 - Estudo de impacto da satisfação no trabalho sobre a produtividade, mediado pela motivação**\n\n1.  A especificação do modelo SEM é feito com uma string(em formato de texto nota que foi usado aspas ou apóstrofos)\n\n2.  Definimos as variáveis latentes\n\n    -   `Satisfação no trabalho` (medida por perguntas sobre ambiente, salário, reconhecimento)\n    -   `Motivação` (medida por perguntas sobre engajamento, metas, esforço)\n    -   `Produtividade` (medida por desempenho, entregas, qualidade)\n\n3.  As equações estruturais são:\n\n    -   `Satisfação → Motivação → Produtividade`\n\n4.  Implementar via software usando R (lavaan package)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# chamar a package\nlibrary(lavaan)\nlibrary(tidyverse)\nlibrary(broom)\n\n\n# step1: simular os dados\nset.seed(123)\n\nn <- 300\nSatisfacao1 <- rnorm(n, mean=5, sd=1)\nSatisfacao2 <- Satisfacao1 + rnorm(n, sd=0.5)\nSatisfacao3 <- Satisfacao1 + rnorm(n, sd=0.5)\n\nMotivacao1 <- 0.6*Satisfacao1 + rnorm(n)\nMotivacao2 <- Motivacao1 + rnorm(n, sd=0.5)\nMotivacao3 <- Motivacao1 + rnorm(n, sd=0.5)\n\nProdutividade1 <- 0.7*Motivacao1 + rnorm(n)\nProdutividade2 <- Produtividade1 + rnorm(n, sd=0.5)\nProdutividade3 <- Produtividade1 + rnorm(n, sd=0.5)\n\ndados <- data.frame(Satisfacao1, Satisfacao2, Satisfacao3,\n                    Motivacao1, Motivacao2, Motivacao3,\n                    Produtividade1, Produtividade2, Produtividade3)\n\n# step2: especificar o modelo com string(texto)\nmodelo <- \"\n  # Variáveis latentes\n  Satisfacao =~ Satisfacao1 + Satisfacao2 + Satisfacao3\n  Motivacao =~ Motivacao1 + Motivacao2 + Motivacao3\n  Produtividade =~ Produtividade1 + Produtividade2 + Produtividade3\n\n  # Relações estruturais\n  Motivacao ~ Satisfacao\n  Produtividade ~ Motivacao\n\"\n\n# step3: Rodar o modelo\nmdl_fit_sem_impact_motiv_prod <- sem(modelo, data = dados)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: lavaan->lav_object_post_check():  \n   some estimated ov variances are negative\n```\n\n\n:::\n\n```{.r .cell-code}\n# step4: Mostrar resultados via summary\nsummary(mdl_fit_sem_impact_motiv_prod, fit.measures = TRUE,\tstandardized = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-19 ended normally after 43 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                        20\n\n  Number of observations                           300\n\nModel Test User Model:\n                                                      \n  Test statistic                                24.186\n  Degrees of freedom                                25\n  P-value (Chi-square)                           0.509\n\nModel Test Baseline Model:\n\n  Test statistic                              3557.984\n  Degrees of freedom                                36\n  P-value                                        0.000\n\nUser Model versus Baseline Model:\n\n  Comparative Fit Index (CFI)                    1.000\n  Tucker-Lewis Index (TLI)                       1.000\n\nLoglikelihood and Information Criteria:\n\n  Loglikelihood user model (H0)              -2549.336\n  Loglikelihood unrestricted model (H1)      -2537.243\n                                                      \n  Akaike (AIC)                                5138.672\n  Bayesian (BIC)                              5212.748\n  Sample-size adjusted Bayesian (SABIC)       5149.320\n\nRoot Mean Square Error of Approximation:\n\n  RMSEA                                          0.000\n  90 Percent confidence interval - lower         0.000\n  90 Percent confidence interval - upper         0.044\n  P-value H_0: RMSEA <= 0.050                    0.977\n  P-value H_0: RMSEA >= 0.080                    0.000\n\nStandardized Root Mean Square Residual:\n\n  SRMR                                           0.018\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nLatent Variables:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  Satisfacao =~                                                         \n    Satisfacao1       1.000                               0.943    0.999\n    Satisfacao2       0.970    0.034   28.678    0.000    0.915    0.881\n    Satisfacao3       0.977    0.035   27.822    0.000    0.922    0.873\n  Motivacao =~                                                          \n    Motivacao1        1.000                               1.183    1.009\n    Motivacao2        0.986    0.025   38.792    0.000    1.166    0.915\n    Motivacao3        0.994    0.026   38.198    0.000    1.176    0.913\n  Produtividade =~                                                      \n    Produtividade1    1.000                               1.296    0.998\n    Produtividade2    1.005    0.022   45.593    0.000    1.303    0.943\n    Produtividade3    1.018    0.023   43.379    0.000    1.319    0.936\n\nRegressions:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  Motivacao ~                                                           \n    Satisfacao        0.629    0.063   10.038    0.000    0.501    0.501\n  Produtividade ~                                                       \n    Motivacao         0.684    0.049   13.890    0.000    0.624    0.624\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n   .Satisfacao1       0.002    0.014    0.118    0.906    0.002    0.002\n   .Satisfacao2       0.241    0.024   10.155    0.000    0.241    0.224\n   .Satisfacao3       0.264    0.025   10.386    0.000    0.264    0.237\n   .Motivacao1       -0.025    0.012   -2.076    0.038   -0.025   -0.018\n   .Motivacao2        0.263    0.024   10.946    0.000    0.263    0.162\n   .Motivacao3        0.276    0.025   11.023    0.000    0.276    0.166\n   .Produtividade1    0.006    0.012    0.463    0.643    0.006    0.003\n   .Produtividade2    0.213    0.021    9.973    0.000    0.213    0.111\n   .Produtividade3    0.245    0.024   10.332    0.000    0.245    0.123\n    Satisfacao        0.890    0.074   12.002    0.000    1.000    1.000\n   .Motivacao         1.048    0.085   12.375    0.000    0.749    0.749\n   .Produtividade     1.025    0.084   12.171    0.000    0.610    0.610\n```\n\n\n:::\n\n```{.r .cell-code}\n# step5: Mostrar resultados arrumados usando broom::tidy() e broom::glance()\n\n# coeficientes de regressão (loadings)\ntidy(mdl_fit_sem_impact_motiv_prod) %>% filter(op==\"~\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 8\n  term                 op    estimate std.error statistic p.value std.lv std.all\n  <chr>                <chr>    <dbl>     <dbl>     <dbl>   <dbl>  <dbl>   <dbl>\n1 Motivacao ~ Satisfa… ~        0.629    0.0626      10.0       0  0.501   0.501\n2 Produtividade ~ Mot… ~        0.684    0.0493      13.9       0  0.624   0.624\n```\n\n\n:::\n\n```{.r .cell-code}\n# principais medidas de ajuste\nglance(mdl_fit_sem_impact_motiv_prod) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 17\n   agfi   AIC   BIC   cfi chisq  npar rmsea rmsea.conf.high   srmr   tli\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>           <dbl>  <dbl> <dbl>\n1 0.969 5139. 5213.     1  24.2    20     0          0.0444 0.0183  1.00\n# ℹ 7 more variables: converged <lgl>, estimator <chr>, ngroups <int>,\n#   missing_method <chr>, nobs <int>, norig <int>, nexcluded <int>\n```\n\n\n:::\n:::\n\n\n\n**Resultados**\n\n-   Cargas fatoriais mostrando como cada indicador representa sua variável latente.\n-   Coeficientes padronizados das relações entre Satisfacao, Motivacao e Produtividade.\n-   Índices de ajuste como RMSEA, CFI, TLI para avaliar a qualidade do modelo.\n\n------------------------------------------------------------------------\n\n**Caso3 - Exemplo em manufatura onde queremos entender por que uma linha de montagem está com baixa produtividade. Suspeitamos que isso tem a ver com treinamento de operadores, qualidade das matérias primas e clima organizacional**\n\nEsses fatores não afetam diretamente a produtividade, mas influenciam a motivação e eficiência operacional, que por sua vez afetam a produtividade.\n\n1.  Vamos simular uma fábrica com as variáveis `treinamento`, `qualidade materia prima`, `clima organizacional`, `motivação`, `eficiência operacional` e `produtividade`.\n\n2.  Vamos definir o modelo `SEM` com relações causais entre essa variáveis.\n\n3.  Ajustar o modelo e gerar um resumo com cargas fatoriais, coeficientes padronizados, índices de ajustes(e.g. CFI, RMSEA, etc)\n\n4.  Implementar via software usando R (lavaan package)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# carregar package\nlibrary(lavaan)\nlibrary(lavaanPlot)\nlibrary(tidyverse)\nlibrary(broom)\n\n# simular dados de manufatura\nset.seed(123)\nn <- 300\n\n# indicadores de variáveis latentes\ntreinamento_1 <- rnorm(n, mean=5, sd=1)\ntreinamento_2 <- treinamento_1 + rnorm(n, sd=0.5)\ntreinamento_3 <- treinamento_1 + rnorm(n, sd=0.5)\n\nqualy_material_1 <- rnorm(n, mean=5, sd=1)\nqualy_material_2 <- qualy_material_1 + rnorm(n, sd=0.5)\nqualy_material_3 <- qualy_material_1 + rnorm(n, sd=0.5)\n\nclima_org_1 <- rnorm(n, mean=5, sd=1)\nclima_org_2 <- clima_org_1 + rnorm(n, sd=0.5)\nclima_org_3 <- clima_org_1 + rnorm(n, sd=0.5)\n\nmotivacao_1 <- 0.6*treinamento_1 + 0.4*clima_org_1 + rnorm(n)\nmotivacao_2 <- motivacao_1 + rnorm(n, sd=0.5)\nmotivacao_3 <- motivacao_1 + rnorm(n, sd=0.5)\n\neficiencia_oper_1 <- 0.5*qualy_material_1 + rnorm(n)\neficiencia_oper_2 <- eficiencia_oper_1 + rnorm(n, sd=0.5)\neficiencia_oper_3 <- eficiencia_oper_1 + rnorm(n, sd=0.5)\n\nprodutividade_1 <- 0.6*motivacao_1 + 0.5*eficiencia_oper_1 + rnorm(n)\nprodutividade_2 <- produtividade_1 + rnorm(n, sd=0.5)\nprodutividade_3 <- produtividade_1 + rnorm(n, sd=0.5)\n\n# jogar dentro do dataframe\ndados <- tibble(treinamento_1, treinamento_2, treinamento_3,\n                qualy_material_1, qualy_material_2, qualy_material_3,\n                clima_org_1, clima_org_2, clima_org_3,\n                motivacao_1, motivacao_2, motivacao_3,\n                eficiencia_oper_1, eficiencia_oper_2, eficiencia_oper_3,\n                produtividade_1, produtividade_2, produtividade_3)\n\n\n# definir o modelo SEM\nmodelo <- \"\n  # variaveis latentes\n  treinamento =~ treinamento_1 + treinamento_2 + treinamento_3\n  qualidade_material =~ qualy_material_1 + qualy_material_2 + qualy_material_3\n  clima_org =~ clima_org_1 + clima_org_2 + clima_org_3\n  motivacao =~ motivacao_1 + motivacao_2 + motivacao_3\n  eficiencia_oper =~ eficiencia_oper_1 + eficiencia_oper_2 + eficiencia_oper_3\n  produtividade =~ produtividade_1 + produtividade_2 + produtividade_3\n\n  # Structural relationships\n  motivacao ~ treinamento + clima_org\n  eficiencia_oper ~ qualidade_material\n  produtividade ~ motivacao + eficiencia_oper\n\"\n\n# Rodar o modelo\nmdl_fit_sem <- sem(modelo, data = dados)\n\n# Mostrar o resumo arrumado com broom::tidy()\ntidy(mdl_fit_sem) %>% filter(op == \"=~\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 18 × 8\n   term                op    estimate std.error statistic p.value std.lv std.all\n   <chr>               <chr>    <dbl>     <dbl>     <dbl>   <dbl>  <dbl>   <dbl>\n 1 treinamento =~ tre… =~       1        0           NA        NA  0.954   1.01 \n 2 treinamento =~ tre… =~       0.949    0.0337      28.2       0  0.905   0.871\n 3 treinamento =~ tre… =~       0.956    0.0349      27.4       0  0.912   0.864\n 4 qualidade_material… =~       1        0           NA        NA  1.03    1.01 \n 5 qualidade_material… =~       1.02     0.0302      33.8       0  1.05    0.901\n 6 qualidade_material… =~       1.02     0.0310      33.0       0  1.05    0.896\n 7 clima_org =~ clima… =~       1        0           NA        NA  1.01    1.000\n 8 clima_org =~ clima… =~       0.982    0.0295      33.3       0  0.990   0.905\n 9 clima_org =~ clima… =~       1.04     0.0314      33.0       0  1.04    0.902\n10 motivacao =~ motiv… =~       1        0           NA        NA  1.26    1.00 \n11 motivacao =~ motiv… =~       0.990    0.0243      40.7       0  1.25    0.927\n12 motivacao =~ motiv… =~       1.04     0.0239      43.3       0  1.31    0.935\n13 eficiencia_oper =~… =~       1        0           NA        NA  1.01    0.988\n14 eficiencia_oper =~… =~       1.05     0.0316      33.4       0  1.06    0.913\n15 eficiencia_oper =~… =~       0.983    0.0318      30.9       0  0.991   0.896\n16 produtividade =~ p… =~       1        0           NA        NA  1.27    0.993\n17 produtividade =~ p… =~       1.05     0.0233      44.8       0  1.33    0.945\n18 produtividade =~ p… =~       1.01     0.0225      45.1       0  1.29    0.945\n```\n\n\n:::\n:::\n\n\n\nPlotar os resultados no diagrama usando `semPlot`\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsemPlot::semPaths(mdl_fit_sem,\n                  what = \"std\",\n                  layout = \"tree\",\n                  sizeMan = 8,\n                  sizeLat = 10,\n                  nCharNodes = 11\n                  )\n```\n\n::: {.cell-output-display}\n![](modelagem_equacoes_estruturais_files/figure-html/sem_produtividade-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n### {{< fa 5 >}} [**Pra onde vai?**]{style=\"color: #5AC8BE ;\"}\n\nDepois de construir e validar o modelo SEM, ele pode ser usado para:\n\n-   Tomada de decisão baseada em evidências como priorizar ações de melhoria com base em dados(e.g investir mais em treinamento se ele tiver alto impacto na produtividade, melhorar políticas de RH).\n-   Apoiar decisões estratégias com evidências estatísticas.\n-   Comunicar resultados de forma clara para diretoria e equipes operacionais.\n-   Integrar SEM com sistemas de qualidade e melhoria contínua(e.g Six Sigma, Lean, TPM)\n-   Publicações científicas que testam teorias complexas.\n-   Desenvolvimento de produtos ou serviços com base em fatores que influenciam comportamento do consumidor.\n-   Avaliação de programas sociais ou educacionais.\n\n### {{< fa 6 >}} [**Qual resultado?**]{style=\"color: #5AC8BE ;\"}\n\n-   Mapeamento claro das causas reais de problemas ou oportunidades.\n-   Modelos visuais e estatísticos que mostram como tudo está conectado.\n-   Redução de desperdícios ao focar em ações que realmente fazem a diferença.\n-   Maior confiança nas decisões pois são baseadas em dados e não apenas em experiência ou opinião.\n-   Modelos estatísticos robustos que explicam bem os dados.\n-   Coeficientes padronizados que mostram a força das relações entre variáveis.\n-   Índices de ajuste (como RMSEA, CFI, TLI) que indicam se o modelo representa bem a realidade.\n-   Insights teóricos e práticos sobre os fatores que influenciam fenômenos complexos.\n",
    "supporting": [
      "modelagem_equacoes_estruturais_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}