<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcelo Carvalho dos Anjos">
<meta name="dcterms.date" content="2025-08-22">

<title>Modelagem de Equações Estruturais – Kaizen &amp; Data Science Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4379b0ccadffce622b03caf4c46266b3.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f3c2ea88cadbcfb37ba28ffa2c97cfc1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ae2d0dcda2edce4ab590422bb373b64f.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Kaizen &amp; Data Science Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Info</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://youtube.com/carvalhoribeiro"> <i class="bi bi-youtube" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/factorialmap"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Conteúdo</h2>
   
  <ul>
  <li><a href="#o-que-é-a-sem" id="toc-o-que-é-a-sem" class="nav-link active" data-scroll-target="#o-que-é-a-sem"><i class="fa-solid fa-1" aria-label="1"></i> <span style="color: #5AC8BE ;"><strong>O que é a SEM</strong></span></a></li>
  <li><a href="#qual-o-objetivo" id="toc-qual-o-objetivo" class="nav-link" data-scroll-target="#qual-o-objetivo"><i class="fa-solid fa-2" aria-label="2"></i> <span style="color: #5AC8BE ;"><strong>Qual o objetivo?</strong></span></a></li>
  <li><a href="#de-onde-vem" id="toc-de-onde-vem" class="nav-link" data-scroll-target="#de-onde-vem"><i class="fa-solid fa-3" aria-label="3"></i> <span style="color: #5AC8BE ;"><strong>De onde vem?</strong></span></a></li>
  <li><a href="#como-fazer" id="toc-como-fazer" class="nav-link" data-scroll-target="#como-fazer"><i class="fa-solid fa-4" aria-label="4"></i> <span style="color: #5AC8BE ;"><strong>Como fazer?</strong></span></a></li>
  <li><a href="#pra-onde-vai" id="toc-pra-onde-vai" class="nav-link" data-scroll-target="#pra-onde-vai"><i class="fa-solid fa-5" aria-label="5"></i> <span style="color: #5AC8BE ;"><strong>Pra onde vai?</strong></span></a></li>
  <li><a href="#qual-resultado" id="toc-qual-resultado" class="nav-link" data-scroll-target="#qual-resultado"><i class="fa-solid fa-6" aria-label="6"></i> <span style="color: #5AC8BE ;"><strong>Qual resultado?</strong></span></a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modelagem de Equações Estruturais</h1>
<p class="subtitle lead">Conceitos e práticas de structural equation modeling SEM usando R</p>
  <div class="quarto-categories">
    <div class="quarto-category">Modelos</div>
  </div>
  </div>



<div class="quarto-title-meta column-page-right">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Marcelo Carvalho dos Anjos </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 22, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="o-que-é-a-sem" class="level3">
<h3 class="anchored" data-anchor-id="o-que-é-a-sem"><i class="fa-solid fa-1" aria-label="1"></i> <span style="color: #5AC8BE ;"><strong>O que é a SEM</strong></span></h3>
<ul>
<li><p><strong>No contexto da manufatura e melhoria de processos</strong>: o SEM é uma ferramenta estatística que ajuda a entender como diferents fatores dentro de um processo estão conectados permitindo analisar várias causas e efeitos ao mesmo tempo, mesmo quando alguns desses fatores não são diretamente medidos(e.g.&nbsp;clima organizacional, engajamento dos operadores, motivação etc).</p></li>
<li><p>É uma abordagem estatística poderosa e flexível que permite investigar relações complexas entre variáveis observadas (dados coletados) e variáveis latentes (conceitos não diretamente mensuráveis, como inteligência ou satisfação), mas que são inferidas a partir de indicadores. Ela combina elementos de análise fatorial e regressão múltipla em um único modelo.</p></li>
<li><p>Diferente dos modelos tradicionais de regressão que analisam uma única equação por vez, o SEM trabalhar com múltiplas equações simultaneamene. O SEM incorpora várias técnicas estatísticas como <code>modelos de regressão linear</code>, <code>modelos de análise fatorial</code>, <code>path analysis</code>, <code>modelos com variáveis latentes</code>, <code>modelos de medição e ponderação</code> e <code>modelos hierárquicos ou multigrupo</code></p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lavaan_sem_models.png" class="img-fluid figure-img"></p>
<figcaption>Modelos disponíveis no pacote lavaan para R</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Clique aqui para expandir detalhes sobre o que são variáveis latentes e variáveis observadas
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Variáveis observadas</strong>: Ajudam a controlar e monitorar o processo. São coisas que conseguimos medir diretamente no chão da fábrica(e.g.&nbsp;temperatura de uma maquina, tempo de produção de uma peça, número de peças com defeito, peso de um produto, horas de treinamento recebidos). Estas variáveis vêm de sensores, relatórios ou medições feitas por pessoas. Elas são vistas e registradas.</p></li>
<li><p><strong>Variáveis latentes</strong>: Ajudam a entender o que está por trás dos resultados e melhorar o sistema de forma mais profunda. São coisas que não conseguimos medir diretamente, mas que influenciam o processo. É necessário usar outras variáveis para estimar ou representá-las(e.g.&nbsp;motivação dos operadores, qualidade do ambiente de trabalho, engajamento com segurança, cultura de melhoria contínua, satisfação com treinamento). Não há um sensor que mede a motivação por exemplo, mas pode-se utilizar de perguntas de uma pesquisa ou observar o comportamentos para representar esse conceito.</p></li>
</ul>
</div>
</div>
</div>
<p>PS. Há conteúdos no Youtube de excelente qualidade que ajudam a compreender melhor esses modelos e suas aplicações como por exemplo, o do professor <span class="citation" data-cites="prof.diogeness.bido2021">Prof. Diogenes S. BIDO (<a href="#ref-prof.diogeness.bido2021" role="doc-biblioref">2021</a>)</span></p>
</section>
<section id="qual-o-objetivo" class="level3">
<h3 class="anchored" data-anchor-id="qual-o-objetivo"><i class="fa-solid fa-2" aria-label="2"></i> <span style="color: #5AC8BE ;"><strong>Qual o objetivo?</strong></span></h3>
<ul>
<li>Identificar relações ocultas entre variáveis de processo, qualidade, produtividade e comportamento humano.</li>
<li>Melhorar decisões com base em dados, não só em intuição.</li>
<li>Validar hipóteses sobre o que realmente afeta o desempenho(e.g.&nbsp;em uma linha de produção, satisfação dos consumidores).</li>
<li>Modelar relações causais entre variáveis.</li>
<li>Testar teorias que envolvem múltiplas dependências simultâneas.</li>
<li>Validar construtos teóricos por meio de dados empíricos.</li>
<li>Avaliar a qualidade de modelos estatísticos complexos.</li>
</ul>
</section>
<section id="de-onde-vem" class="level3">
<h3 class="anchored" data-anchor-id="de-onde-vem"><i class="fa-solid fa-3" aria-label="3"></i> <span style="color: #5AC8BE ;"><strong>De onde vem?</strong></span></h3>
<p>Na academia, o SEM surgiu para estudar fenômenos complexos como comportamento humano, educação e psicologia onde foi desenvolvido a partir da evolução da análise fatorial e da path analysis (análise de caminhos), ganhando força nas ciências sociais, psicologia, marketing e educação.</p>
<p>A necessidade surgiu da limitação de métodos estatísticos tradicionais (como regressão simples ou múltipla) que não conseguiam: - Capturar relações simultâneas entre múltiplas variáveis. - Trabalhar com variáveis latentes (não diretamente mensuráveis). - Testar modelos teóricos complexos com múltiplas etapas e dependências.</p>
<p>Na industria onde há sistemas igualmente complexos como uma fábrica com centenas de variáveis interagindo. Ela surge como ferramenta complementar a métodos tradicionais(e.g.&nbsp;gráficos de controle, regressão simples etc) os quais podem não conseguir capturar todas as complexidades existentes no processo. O SEM entra como uma solução para modelar sistemas industriais de forma mais completa.</p>
</section>
<section id="como-fazer" class="level3">
<h3 class="anchored" data-anchor-id="como-fazer"><i class="fa-solid fa-4" aria-label="4"></i> <span style="color: #5AC8BE ;"><strong>Como fazer?</strong></span></h3>
<p>Antes de iniciarmos nos exemplos é importante notar as diferentes sintaxes no pacote <code>lavaan</code> como <code>~</code> significa previsão(predict), <code>=~</code> significa indicador(indicator). E também as definições das palavras(e.g <code>variável exógena</code>, <code>fator</code> etc.)</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Clique aqui para mais detalhes sobre as sintaxes usadas no lavaan
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>fórmulas e sintaxes</strong></p>
<ul>
<li><p><code>~</code> significa prever ou predict e é usado para regressõ do resultado observado aos preditores observados(e.g.&nbsp;lm(mpg~wt, data = mtcars)).</p></li>
<li><p><code>=~</code> significa indicador(indicator) e é usada para a variável latente para indicador observado em modelos SEM(e.g.&nbsp;f =~ q + r + s)</p></li>
<li><p><code>~~</code> significa covariância(e.g.&nbsp;x~~x), que neste caso é variância por está interagindo com ela mesma.</p></li>
<li><p><code>~1</code> significa intercepto(e.g.&nbsp;x~1 estima média da variável x)</p></li>
<li><p><code>1*</code> significa corrige parametro ou carga(e.g.&nbsp;f =~1*q)</p></li>
<li><p><code>NA*</code> significa liberar o parâmetro ou carga(e.g.&nbsp;f=~NA*q), e é util para substituir o marcados padrão.</p></li>
<li><p><code>a*</code> significa rotular o parâmetro ‘a’ usado para restrições do modelo(e.g.&nbsp;f=~a*q)</p></li>
</ul>
<hr>
<p><strong>tipos de variáveis e resultados</strong></p>
<ul>
<li><strong>variável observada</strong>: é algo que a gente consegue medir ou ver diretamente(e.g.&nbsp;quantas peças um funcionário produz por hora)</li>
<li><strong>variável latente</strong>: é algo que a gente não consegue medir diretamente, mas que deduzimos com base em outras coisas(e.g.&nbsp;satisfação no trabalho de alguém).</li>
<li><strong>variável exógena</strong>: é uma causa. Ela influencia outra coisa, mas não é influenciada por ela(e.g pense na “experiência” de um funcionário).</li>
<li><strong>variável endógena</strong>: é um efeito. Ela é influenciada por outras coisas(e.g a “produtividade” de um funcionário).</li>
<li><strong>modelo de medição</strong>: é como a gente liga o que a gente vê (variáveis observadas) com o que a gente não vê diretamente(variáveis latentes).</li>
<li><strong>indicador</strong>: é o que a gente usa pra medir algo que não vemos. Se a “satisfação” é o que não vemos, o “número de reclamações” pode ser um indicador.</li>
<li><strong>fator</strong>: é o que a gente não vê, mas que é formado por várias coisas que a gente mede(e.g a “qualidade” é um fator, medido por “defeitos”, “rejeitos”, etc).</li>
<li><strong>carga fatorial</strong>: é o quanto uma coisa medida contribui para formar o que a gente não vê(e.g.&nbsp;tipo a “força” da ligação).</li>
<li><strong>modelo estrutural</strong>: é como a gente mostra as relações de causa e efeito entre as coisas que estudamos.</li>
<li><strong>regression path</strong>: é a seta que mostra a influência direta de uma coisa sobre outra.</li>
</ul>
<hr>
<p><strong>diagrama</strong></p>
<ul>
<li><strong>retangulos/quadrados</strong> representa que a variável é observada</li>
<li><strong>circulos</strong> representa que a variável é latente</li>
<li><strong>traço com seta de um lado</strong> representa o caminho da causa e efeito</li>
<li><strong>traço com seta dos dois lados</strong> representa a covariância ou variância(quando ela estiver em si mesma)</li>
</ul>
</div>
</div>
</div>
<p><strong>Caso1 - Prever milhas por galão e tempo de aceleração de veículos</strong></p>
<p>Iremos fazer um modelo <code>path analysis</code> de regressão multivariada (duas variáveis de resposta) com variáveis observadas(neste não terá variáveis latentes), apenas para ilustrar de forma simples o problema e a solução. Para isso usaremos o conjunto de dados <code>mtcars</code> que é bem conhecido por quem usa o <code>R</code></p>
<ol type="1">
<li>A especificação do modelo SEM é feito com uma string(em formato de texto), note que foi usado aspas indicado que o formato é texto, onde háduas equações estruturais.
<ul>
<li><strong>mpg ~ cyl + disp + hp</strong>: o consumo de combustível (mpg) é explicado por número de cilindros (cyl), deslocamento (disp) e potência (hp).</li>
<li><strong>qsec ~ disp + hp + wt</strong>: o tempo de aceleração (qsec) é explicado por deslocamento (disp), potência (hp) e peso (wt).</li>
</ul></li>
<li>Rodar o modelo usando R/RStudio <span class="citation" data-cites="rstudio/2025"><em>Rstudio/Rstudio</em> (<a href="#ref-rstudio/2025" role="doc-biblioref">2025</a>)</span>, Lavaan package <span class="citation" data-cites="rosseel2024">Rosseel (<a href="#ref-rosseel2024" role="doc-biblioref">2024</a>)</span>, Quarto Publishing <span class="citation" data-cites="quarto2025"><span>“Quarto”</span> (<a href="#ref-quarto2025" role="doc-biblioref">2025</a>)</span> e mostrar os resultados.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaanPlot)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># step1: especificação do modelo SEM</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>mdl_spec_sem_mtcas <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="st">mpg ~ cyl + disp + hp</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="st">qsec ~ disp + hp + wt</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># step2: rodar o modelo e mostrar resultados</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># rodar o modelo</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>mdl_fit_sem_mtcars <span class="ot">&lt;-</span> <span class="fu">sem</span>(mdl_spec_sem_mtcas, <span class="at">data =</span> mtcars)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># mostrar os resultados</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl_fit_sem_mtcars, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 32 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         9

  Number of observations                            32

Model Test User Model:
                                                      
  Test statistic                                18.266
  Degrees of freedom                                 2
  P-value (Chi-square)                           0.000

Model Test Baseline Model:

  Test statistic                               101.965
  Degrees of freedom                                 9
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.825
  Tucker-Lewis Index (TLI)                       0.213

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)               -124.003
  Loglikelihood unrestricted model (H1)       -114.870
                                                      
  Akaike (AIC)                                 266.005
  Bayesian (BIC)                               279.197
  Sample-size adjusted Bayesian (SABIC)        251.140

Root Mean Square Error of Approximation:

  RMSEA                                          0.504
  90 Percent confidence interval - lower         0.309
  90 Percent confidence interval - upper         0.727
  P-value H_0: RMSEA &lt;= 0.050                    0.000
  P-value H_0: RMSEA &gt;= 0.080                    1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.041

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                   Estimate   Std.Err  z-value  P(&gt;|z|)   Std.lv   Std.all
  mpg ~                                                                   
    cyl               -0.987    0.738   -1.337    0.181    -0.987   -0.293
    disp              -0.021    0.010   -2.178    0.029    -0.021   -0.435
    hp                -0.017    0.014   -1.218    0.223    -0.017   -0.190
  qsec ~                                                                  
    disp              -0.008    0.004   -2.122    0.034    -0.008   -0.559
    hp                -0.023    0.004   -5.229    0.000    -0.023   -0.849
    wt                 1.695    0.398    4.256    0.000     1.695    0.908

Covariances:
                   Estimate   Std.Err  z-value  P(&gt;|z|)   Std.lv   Std.all
 .mpg ~~                                                                  
   .qsec               0.447    0.511    0.874    0.382     0.447    0.156

Variances:
                   Estimate   Std.Err  z-value  P(&gt;|z|)   Std.lv   Std.all
   .mpg                8.194    2.049    4.000    0.000     8.194    0.234
   .qsec               0.996    0.249    4.000    0.000     0.996    0.308</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Clique aqui para mais detalhes sobre a interpretação dos resultados do modelo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Interpretação da Saída:</strong></p>
<p><strong>1. Informações Básicas do Modelo:</strong></p>
<ul>
<li><strong><code>lavaan 0.6-19 ended normally after 32 iterations</code></strong>: O processo de estimação do modelo convergiu com sucesso após 32 iterações. Isso é bom, indica que o algoritmo encontrou uma solução estável.</li>
<li><strong><code>Estimator ML</code></strong>: O estimador usado foi o de Máxima Verossimilhança (Maximum Likelihood). Este é o estimador padrão e mais comum para SEM quando os dados são aproximadamente normais.</li>
<li><strong><code>Optimization method NLMINB</code></strong>: O método de otimização usado.</li>
<li><strong><code>Number of model parameters 9</code></strong>: O modelo possui 9 parâmetros que foram estimados(e.g.&nbsp;os coeficientes de caminho, variâncias residuais, covariâncias).</li>
<li><strong><code>Number of observations 32</code></strong>: Foi usado um conjunto de dados com 32 observações (linhas), que é o tamanho do conjunto de dados <code>mtcars</code>.</li>
</ul>
<p><strong>2. Teste do Modelo do Usuário (<code>Model Test User Model</code>):</strong></p>
<p>Este é o teste de qui-quadrado (Chi-square test) do nosso modelo. A hipótese nula (<span class="math inline">\(H_0\)</span>) deste teste é que o nosso modelo se ajusta <em>perfeitamente</em> aos dados da população. Uma hipótese alternativa (<span class="math inline">\(H_1\)</span>) é que o modelo não se ajusta perfeitamente.</p>
<ul>
<li><p><strong><code>Test statistic 18.266</code></strong>: O valor do teste de qui-quadrado.</p></li>
<li><p><strong><code>Degrees of freedom 2</code></strong>: Os graus de liberdade do nosso modelo.</p></li>
<li><p><strong><code>P-value (Chi-square) 0.000</code></strong>: O p-valor associado.</p>
<p><strong>Interpretação:</strong> Como o p-valor (0.000) é menor que 0.05 (ou qualquer nível de significância usual), nós <strong>rejeitamos a hipótese nula</strong>. Isso significa que o nosso modelo (o “modelo do usuário”) <em>não</em> se ajusta perfeitamente aos dados observados.</p>
<p><strong>Cuidado:</strong> Embora isso possa parecer uma má notícia, o teste de qui-quadrado é muito sensível, especialmente com tamanhos de amostra maiores. Com 32 observações, a rejeição aqui é um sinal de que o modelo não é <em>perfeito</em>. No entanto, em SEM, raramente esperamos um ajuste perfeito. O foco geralmente é em ter um “bom ajuste” ou um “ajuste razoável”, avaliado por outros índices de ajuste.</p></li>
</ul>
<p><strong>3. Teste do Modelo de Linha de Base (<code>Model Test Baseline Model</code>):</strong></p>
<p>O modelo de linha de base (baseline model) é um modelo nulo onde todas as variáveis são consideradas não correlacionadas. Serve como um ponto de comparação para o nosso modelo.</p>
<ul>
<li><p><strong><code>Test statistic 101.965</code></strong></p></li>
<li><p><strong><code>Degrees of freedom 9</code></strong></p></li>
<li><p><strong><code>P-value 0.000</code></strong></p>
<p><strong>Interpretação:</strong> O modelo de linha de base também não se ajusta bem aos dados (p-valor &lt; 0.05), o que é esperado, pois é um modelo muito restritivo. Este teste é usado principalmente para calcular os índices de ajuste comparativos (CFI, TLI).</p></li>
</ul>
<p><strong>4. Modelo do Usuário versus Modelo de Linha de Base (<code>User Model versus Baseline Model</code>):</strong></p>
<p>Esses são índices de ajuste incrementais, que comparam o nosso modelo com o modelo de linha de base.</p>
<ul>
<li><p><strong><code>Comparative Fit Index (CFI) 0.825</code></strong>:</p>
<ul>
<li><strong>Interpretação:</strong> O CFI varia de 0 a 1. Valores acima de 0.90 ou 0.95 são geralmente considerados indicativos de um bom ajuste. Nosso CFI de 0.825 está abaixo dos critérios comuns para um bom ajuste (geralmente &gt; 0.90 ou &gt; 0.95). Isso sugere que o nosso modelo não melhora substancialmente o ajuste em comparação com o modelo nulo o suficiente para ser considerado um “bom” ajuste.</li>
</ul></li>
<li><p><strong><code>Tucker-Lewis Index (TLI) 0.213</code></strong>:</p>
<ul>
<li><strong>Interpretação:</strong> O TLI (também conhecido como NNFI) é outro índice incremental, também variando geralmente de 0 a 1, com valores &gt; 0.90 ou &gt; 0.95 indicando bom ajuste. Seu TLI de 0.213 é <strong>muito baixo</strong>, indicando um ajuste pobre do modelo.</li>
</ul>
<p><strong>Em resumo para CFI e TLI:</strong> Ambos os índices sugerem que o nosso modelo não está bem ajustado aos dados.</p></li>
</ul>
<p><strong>5. Critérios de Log-Verossimilhança e Informação (<code>Loglikelihood and Information Criteria</code>):</strong></p>
<p>Esses critérios são usados para comparar modelos, favorecendo modelos com melhor ajuste e menor complexidade. Valores menores são geralmente preferíveis.</p>
<ul>
<li><p><strong><code>Loglikelihood user model (H0) -124.003</code></strong>: A log-verossimilhança do nosso modelo.</p></li>
<li><p><strong><code>Loglikelihood unrestricted model (H1) -114.870</code></strong>: A log-verossimilhança do modelo não restrito (também conhecido como modelo saturado), que é o modelo com o melhor ajuste possível aos dados.</p></li>
<li><p><strong><code>Akaike (AIC) 266.005</code></strong>: Critério de Informação de Akaike.</p></li>
<li><p><strong><code>Bayesian (BIC) 279.197</code></strong>: Critério de Informação Bayesiano.</p></li>
<li><p><strong><code>Sample-size adjusted Bayesian (SABIC) 251.140</code></strong>: BIC ajustado para o tamanho da amostra.</p>
<p><strong>Interpretação:</strong> Esses valores são mais úteis para comparar nosso modelo com modelos alternativos (modelos aninhados ou não aninhados). Modelos com valores menores de AIC, BIC e SABIC são considerados melhores. Isoladamente, eles não indicam “bom” ou “mau” ajuste.</p></li>
</ul>
<p><strong>6. Erro Quadrático Médio da Aproximação (<code>Root Mean Square Error of Approximation</code> - RMSEA):</strong></p>
<p>O RMSEA é um índice de ajuste absoluto que mede o quão mal o modelo se ajusta aos dados. Valores menores indicam melhor ajuste.</p>
<ul>
<li><strong><code>RMSEA 0.504</code></strong>:
<ul>
<li><strong>Interpretação:</strong> Um RMSEA &lt; 0.05 é considerado um bom ajuste, entre 0.05 e 0.08 é um ajuste razoável, e &gt; 0.10 é um ajuste pobre. Nosso valor de 0.504 é <strong>extremamente alto</strong>, indicando um ajuste muito ruim do modelo aos dados.</li>
</ul></li>
<li><strong><code>90 Percent confidence interval - lower 0.309</code></strong></li>
<li><strong><code>90 Percent confidence interval - upper 0.727</code></strong>: O intervalo de confiança para o RMSEA é muito amplo e totalmente acima de 0.08, reforçando o mau ajuste.</li>
<li><strong><code>P-value H_0: RMSEA &lt;= 0.050 0.000</code></strong>: Este é o p-valor para o teste da hipótese nula de que o RMSEA é menor ou igual a 0.05. Como é 0.000, rejeitamos essa hipótese.</li>
<li><strong><code>P-value H_0: RMSEA &gt;= 0.080 1.000</code></strong>: Este é o p-valor para o teste da hipótese nula de que o RMSEA é maior ou igual a 0.08. Como é 1.000, não podemos rejeitar essa hipótese, o que significa que é muito provável que seu RMSEA seja realmente &gt;= 0.08.</li>
</ul>
<p><strong>Em resumo para RMSEA:</strong> O RMSEA confirma que o modelo tem um ajuste muito pobre aos dados.</p>
<hr>
<p><strong>Tabela de Regressão</strong></p>
<p>É a parte mais importante da saída para entender as relações específicas do modelo SEM. Ela detalha os coeficientes estimados para cada caminho (regressão), covariância e variância**</p>
<hr>
<p><strong>1. Informações sobre Erros Padrão (<code>Standard errors</code>):</strong></p>
<ul>
<li><p><strong><code>Standard errors Standard</code></strong>: Indica que os erros padrão foram calculados usando o método padrão (não robusto).</p></li>
<li><p><strong><code>Information Expected</code></strong>: O tipo de matriz de informação utilizada na estimação (esperada).</p></li>
<li><p><strong><code>Information saturated (h1) model Structured</code></strong>: Refere-se a como a matriz de informação é tratada para o modelo saturado (h1).</p>
<p><strong>Interpretação:</strong> Essas são informações técnicas sobre como os erros padrão e os testes de significância foram calculados. Geralmente não é necessário se aprofundar muito nisso, a menos que haja problemas de convergência ou preocupações com a normalidade dos dados.</p></li>
</ul>
<p><strong>2. Regressões (<code>Regressions</code>):</strong></p>
<p>Esta seção mostra os efeitos diretos (caminhos) de uma variável sobre outra, semelhantes aos coeficientes de regressão.</p>
<ul>
<li><strong><code>Estimate</code></strong>: O coeficiente de regressão(não padronizado). Representa a mudança na variável dependente para cada unidade de mudança na variável preditora, mantendo as outras preditoras constantes.</li>
<li><strong><code>Std.Err</code></strong>: O erro padrão do coeficiente estimado.</li>
<li><strong><code>z-value</code></strong>: O valor Z do teste de Wald, que é o <code>Estimate</code> dividido pelo <code>Std.Err</code>. É usado para testar a significância estatística do coeficiente.</li>
<li><strong><code>P(&gt;|z|)</code></strong>: O p-valor associado ao valor Z. Se for menor que seu nível de significância (geralmente 0.05), o coeficiente é considerado estatisticamente significativo.</li>
<li><strong><code>Std.lv</code></strong>: Coeficientes padronizados com base apenas nas variáveis latentes (se houver). Neste modelo, como você só tem variáveis observadas, será o mesmo que <code>Estimate</code>.</li>
<li><strong><code>Std.all</code></strong>: Coeficientes padronizados com base em todas as variáveis (observadas e latentes). Estes são os que você vê no diagrama e são os mais úteis para comparar a força relativa dos efeitos. Eles variam de -1 a 1.</li>
</ul>
<p><strong>Detalhes da Interpretação:</strong></p>
<p><strong>a) <code>mpg ~ cyl</code> (mpg é predito por cyl):</strong> * <code>Estimate = -0.987</code>: Para cada aumento de 1 cilindro, o <code>mpg</code> diminui em 0.987 unidades. * <code>P(&gt;|z|) = 0.181</code>: Não é significativo (p &gt; 0.05). Isso significa que o número de cilindros não tem um efeito direto estatisticamente significativo sobre <code>mpg</code>, após contabilizar as outras variáveis no modelo para <code>mpg</code>. * <code>Std.all = -0.293</code>: Um efeito padronizado fraco a moderado, mas não significativo. (Corresponde a <code>-0.29</code> no diagrama).</p>
<p><strong>b) <code>mpg ~ disp</code> (mpg é predito por disp):</strong> * <code>Estimate = -0.021</code>: Para cada aumento de 1 unidade em <code>disp</code>, o <code>mpg</code> diminui em 0.021 unidades. * <code>P(&gt;|z|) = 0.029</code>: <strong>Significativo</strong> (p &lt; 0.05). <code>disp</code> tem um efeito direto negativo estatisticamente significativo sobre <code>mpg</code>. * <code>Std.all = -0.435</code>: Um efeito padronizado moderado e significativo. (Corresponde a <code>-0.44</code> no diagrama).</p>
<p><strong>c) <code>mpg ~ hp</code> (mpg é predito por hp):</strong> * <code>Estimate = -0.017</code>: Para cada aumento de 1 unidade em <code>hp</code>, o <code>mpg</code> diminui em 0.017 unidades. * <code>P(&gt;|z|) = 0.223</code>: Não é significativo (p &gt; 0.05). <code>hp</code> não tem um efeito direto estatisticamente significativo sobre <code>mpg</code> após contabilizar as outras variáveis. * <code>Std.all = -0.190</code>: Um efeito padronizado fraco e não significativo. (Corresponde a <code>-0.19</code> no diagrama).</p>
<p><strong>d) <code>qsec ~ disp</code> (qsec é predito por disp):</strong> * <code>Estimate = -0.008</code>: Para cada aumento de 1 unidade em <code>disp</code>, o <code>qsec</code> diminui em 0.008 unidades. * <code>P(&gt;|z|) = 0.034</code>: <strong>Significativo</strong> (p &lt; 0.05). <code>disp</code> tem um efeito direto negativo estatisticamente significativo sobre <code>qsec</code>. * <code>Std.all = -0.559</code>: Um efeito padronizado forte e significativo. (Corresponde a <code>-0.56</code> no diagrama).</p>
<p><strong>e) <code>qsec ~ hp</code> (qsec é predito por hp):</strong> * <code>Estimate = -0.023</code>: Para cada aumento de 1 unidade em <code>hp</code>, o <code>qsec</code> diminui em 0.023 unidades. * <code>P(&gt;|z|) = 0.000</code>: <strong>Altamente significativo</strong> (p &lt; 0.001). <code>hp</code> tem um efeito direto negativo muito forte e estatisticamente significativo sobre <code>qsec</code>. * <code>Std.all = -0.849</code>: Um efeito padronizado muito forte e significativo. (Corresponde a <code>-0.85</code> no diagrama).</p>
<p><strong>f) <code>qsec ~ wt</code> (qsec é predito por wt):</strong> * <code>Estimate = 1.695</code>: Para cada aumento de 1 unidade em <code>wt</code>, o <code>qsec</code> aumenta em 1.695 unidades. * <code>P(&gt;|z|) = 0.000</code>: <strong>Altamente significativo</strong> (p &lt; 0.001). <code>wt</code> tem um efeito direto positivo muito forte e estatisticamente significativo sobre <code>qsec</code>. * <code>Std.all = 0.908</code>: Um efeito padronizado muito forte e significativo. (Corresponde a <code>0.91</code> no diagrama).</p>
<p><strong>Resumo das Regressões:</strong> * Para <code>mpg</code>, apenas <code>disp</code> tem um efeito direto significativo (e negativo). * Para <code>qsec</code>, <code>disp</code>, <code>hp</code> e <code>wt</code> têm efeitos diretos significativos. <code>hp</code> (negativo) e <code>wt</code> (positivo) são os preditores mais fortes de <code>qsec</code>.</p>
<p><strong>3. Covariâncias (<code>Covariances</code>):</strong></p>
<p>Esta seção mostra as covariâncias estimadas entre variáveis que não têm uma relação causal direta modelada (ou entre os resíduos das variáveis endógenas).</p>
<ul>
<li><p><strong><code>.mpg ~~ .qsec</code> (Covariância entre os resíduos de mpg e qsec):</strong></p>
<ul>
<li><code>Estimate = 0.447</code>: A covariância não padronizada dos resíduos.</li>
<li><code>P(&gt;|z|) = 0.382</code>: Não é significativo (p &gt; 0.05).</li>
<li><code>Std.all = 0.156</code>: Uma correlação residual padronizada fraca e não significativa. (Corresponde a <code>0.16</code> no diagrama, que é a correlação entre os resíduos, não as variáveis brutas).</li>
</ul>
<p><strong>Interpretação:</strong> A covariância (ou correlação) entre os resíduos de <code>mpg</code> e <code>qsec</code> não é estatisticamente significativa. Isso significa que, após contabilizar os efeitos das variáveis preditoras (<code>cyl</code>, <code>disp</code>, <code>hp</code> para <code>mpg</code>; <code>disp</code>, <code>hp</code>, <code>wt</code> para <code>qsec</code>), qualquer variância restante em <code>mpg</code> e <code>qsec</code> não está significativamente relacionada entre si.</p></li>
</ul>
<p><strong>4. Variâncias (<code>Variances</code>):</strong></p>
<p>Esta seção mostra as variâncias estimadas para as variáveis exógenas(chamada de causas ou variáveis preditoras) e as variâncias residuais para as variáveis endógenas(chamadas de efeito ou variáveis de resposta).</p>
<ul>
<li><p><strong><code>.mpg</code> (Variância residual de mpg):</strong></p>
<ul>
<li><code>Estimate = 8.194</code>: A variância não padronizada do resíduo de <code>mpg</code>.</li>
<li><code>P(&gt;|z|) = 0.000</code>: Altamente significativo, o que é esperado para variâncias.</li>
<li><code>Std.all = 0.234</code>: A variância residual padronizada (1 - R-quadrado). Isso significa que 23.4% da variância de <code>mpg</code> não é explicada pelas preditoras no modelo. Consequentemente, as preditoras (<code>cyl</code>, <code>disp</code>, <code>hp</code>) explicam <code>1 - 0.234 = 0.766</code> ou 76.6% da variância em <code>mpg</code> (R-quadrado para <code>mpg</code>). (Corresponde a <code>0.23</code> no diagrama).</li>
</ul></li>
<li><p><strong><code>.qsec</code> (Variância residual de qsec):</strong></p>
<ul>
<li><code>Estimate = 0.996</code>: A variância não padronizada do resíduo de <code>qsec</code>.</li>
<li><code>P(&gt;|z|) = 0.000</code>: Altamente significativo.</li>
<li><code>Std.all = 0.308</code>: A variância residual padronizada (1 - R-quadrado). Isso significa que 30.8% da variância de <code>qsec</code> não é explicada pelas preditoras no modelo. Consequentemente, as preditoras (<code>disp</code>, <code>hp</code>, <code>wt</code>) explicam <code>1 - 0.308 = 0.692</code> ou 69.2% da variância em <code>qsec</code> (R-quadrado para <code>qsec</code>). (Corresponde a <code>0.31</code> no diagrama).</li>
</ul>
<p><strong>Interpretação:</strong> As variâncias residuais indicam a proporção da variância das variáveis dependentes que <em>não</em> é explicada pelo modelo. Os valores padronizados (<code>Std.all</code>) fornecem o complementar do R-quadrado. nosso modelo explica uma proporção razoável da variância em ambas as variáveis dependentes.</p></li>
</ul>
<p><strong>Considerações Finais:</strong></p>
<p>Lembre-se da interpretação anterior sobre o ajuste geral do modelo. Embora alguns caminhos individuais sejam estatisticamente significativos e os Rs-quadrados sejam razoáveis, os índices de ajuste globais (CFI, TLI, RMSEA) indicaram que o modelo como um todo não se ajusta bem aos dados. Isso significa que, embora as relações específicas que você encontrou sejam interessantes, a estrutura geral do nosso modelo pode não ser a melhor representação dos dados, possivelmente devido ao pequeno tamanho da amostra ou a um modelo teórico incompleto/incorreto.</p>
<p>Em resumo, nosso modelo atual não se ajusta bem aos dados. A primeira etapa é sempre revisar a teoria por trás do nosso modelo e a especificação no <code>lavaan</code>. Dada a pequena amostra do <code>mtcars</code>, é desafiador construir um modelo SEM robusto com este conjunto de dados, eu apenas usei ele para facilitar o entendimento para quem está vendo esse conteúdo pela primeira vez, mas que já conheça o <code>mtcars</code> de outros exemplos.</p>
<p><strong>Conclusão Geral e Recomendações:</strong></p>
<p>Com base em todos os índices de ajuste (Chi-quadrado, CFI, TLI, RMSEA), nosso modelo atual apresenta um ajuste muito pobre aos dados do <code>mtcars</code>. Isso significa que as relações e a estrutura que nós hipotetizamos em nosso diagrama (e que o <code>lavaan</code> tentou ajustar) não representam bem as covariâncias observadas no conjunto de dados.</p>
<p><strong>O que fazer a seguir?</strong></p>
<ol type="1">
<li><strong>Revisar o Modelo Teórico:</strong>
<ul>
<li>nosso modelo SEM deve ser baseado em teoria. As relações que desenhamos fazem sentido conceitualmente?</li>
<li>Há alguma variável importante faltando no modelo que poderia explicar melhor <code>mpg</code> ou <code>qsec</code>?</li>
<li>Será que incluímos todas as covariâncias entre as variáveis preditoras(<code>cyl</code>, <code>disp</code>, <code>hp</code>, <code>wt</code>) que são esperadas? (Pelo diagrama, parece que sim, mas verificar se o modelo <code>lavaan</code> as especificou corretamente, é uma boa coisa a se fazer).</li>
</ul></li>
<li><strong>Verificar Especificação do Modelo:</strong>
<ul>
<li>Certificar de que a sintaxe do <code>lavaan</code> reflete exatamente o diagrama que nós pretendiamos testar. Às vezes, pequenos erros de digitação ou omissões podem levar a um ajuste ruim.</li>
<li>Se nós usamos um atalho como <code>x ~~ y</code> para covariância ou <code>y ~ x</code> para regressão, confirir se não há setas ou covariâncias que deveriam estar lá mas não foram especificadas, também é uma boa prática.</li>
</ul></li>
<li><strong>Explorar Modificações, mas com Cuidado:</strong>
<ul>
<li>O <code>lavaan</code> pode fornecer índices de modificação (<code>modindices()</code>) que sugerem quais parâmetros (caminhos ou covariâncias) poderiam ser adicionados ao modelo para melhorar o ajuste.</li>
<li><strong>Importante:</strong> Use índices de modificação com muita cautela e apenas se as modificações fizerem sentido teórico. Fazer mudanças apenas para melhorar o ajuste sem base teórica pode levar a um modelo superajustado aos dados da amostra e que não generaliza bem.</li>
</ul></li>
<li><strong>Tamanho da Amostra:</strong>
<ul>
<li>Com 32 observações, nós temos um tamanho de amostra muito pequeno para SEM. Modelos SEM geralmente exigem amostras maiores (centenas de observações) para ter poder estatístico adequado e para que os índices de ajuste funcionem de forma confiável. Um tamanho de amostra pequeno pode inflar o qui-quadrado e dificultar a obtenção de um bom ajuste, mesmo que o modelo seja teoricamente correto. No caso do <code>mtcars</code>, que tem apenas 32 carros, as limitações do conjunto de dados são um fator importante.</li>
</ul></li>
<li><strong>Multicolinearidade:</strong>
<ul>
<li>No diagrama, vimos correlações muito altas entre <code>cyl</code>, <code>disp</code>, <code>hp</code>, <code>wt</code>. Isso também pode ser observado, se nos plotarmos um gráfico de correlação. Embora SEM possa lidar com isso melhor do que regressão múltipla tradicional, correlações extremamente altas ainda podem dificultar a estimação ou interpretação dos efeitos diretos.</li>
</ul></li>
</ol>
<p><strong>Conexão com o Diagrama abaixo</strong></p>
<p>Os valores na coluna <code>Std.all</code> correspondem diretamente aos números exibidos nas setas do nosso diagrama (<code>semPlot</code>). A espessura das setas no diagrama visualmente representa a magnitude desses <code>Std.all</code>. A cor (verde/vermelho) reflete o sinal do <code>Estimate</code> (positivo/negativo).</p>
</div>
</div>
</div>
<p>Agora, vamos plotar os resultados no diagrama usando o pacote <code>semPlot</code> <span class="citation" data-cites="epskamp2025">Epskamp (<a href="#ref-epskamp2025" role="doc-biblioref">2025</a>)</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Gerar o diagrama de caminhos</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(mdl_fit_sem_mtcars, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">what =</span> <span class="st">"std"</span>,         <span class="co"># mostra coeficientes padronizados</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">layout =</span> <span class="st">"tree"</span>,      <span class="co"># organiza em formato de árvore</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.2</span>, <span class="co"># tamanho dos rótulos</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">8</span>,          <span class="co"># tamanho dos nós</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeLat =</span> <span class="dv">10</span>,         <span class="co"># tamanho das variáveis latentes(não tem nesse modelo)</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="modelagem_equacoes_estruturais_files/figure-html/semplot_mtcars-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Clique aqui pra expandir se precisar da interpretação do gráfico
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>O diagrama de caminho (path diagram) acima, representa as relações hipotéticas entre variáveis usando o conjunto de dados <code>mtcars</code>.</p>
<p><strong>Visão Geral do Diagrama:</strong></p>
<ul>
<li><p><strong>Variáveis Observadas (Retângulos):</strong> representa uma variável observada do conjunto de dados <code>mtcars</code>(e.g cyl(número de cilindros), disp(cilindrada),hp(potência),wt(peso do veículo), mpg(milhas por galão), qsec(tempo de 1/4 de milha). Se tivessemos variáveis latentes elas apareceriam em círculos.</p></li>
<li><p><strong>Setas e Linhas:</strong> representam relações causais ou diretivas (regressões), enquanto as linhas bidirecionais curvas representam covariâncias ou correlações.</p></li>
<li><p><strong>Cores:</strong> Verde indica uma relação positiva, enquanto a vermelha, relação negativa.</p></li>
<li><p><strong>Espessura da Linha/Seta:</strong> É proporcional à magnitude do coeficiente de caminho (seja ele um coeficiente de regressão ou uma correlação). Linhas mais grossas indicam relações mais fortes.</p></li>
<li><p><strong>Números nas Setas/Linhas:</strong> são os coeficientes de caminho padronizados (standardized path coefficients), que são análogos a coeficientes de regressão padronizados ou correlações. Eles variam de -1 a 1. Onde valores próximos a 0 indicam relações fracas e valores próximos a 1 (ou -1) indicam relações fortes.</p></li>
</ul>
<p><strong>Interpretação detalhada por seções:</strong></p>
<p><strong>1. Relações entre as variáveis de “características do carro” (Topo):</strong></p>
<ul>
<li><strong>Setas Bidirecionais Curvas na Parte Superior (entre cyl, disp, hp, wt):</strong> Estas representam as correlações entre essas variáveis de características do carro. Todas são verdes e têm valores altos, indicando fortes correlações positivas.
<ul>
<li><code>cyl &lt;-&gt; cyl</code> (1.00): Isso é o “erro” ou variância não explicada da própria variável. Em modelos SEM, geralmente é a variância residual ou a variância de um erro, mas para variáveis exógenas (sem setas apontando para elas), pode representar a variância total. No entanto, o <code>semPlot</code> pode desenhar isso como a variância total de uma variável quando não há preditores, ou a variância residual de uma variável endógena. Neste caso, para <code>cyl</code>, <code>disp</code>, <code>hp</code>, <code>wt</code> que parecem ser variáveis exógenas (ou seja, suas causas não são modeladas aqui, elas são as preditoras), esse <code>1.00</code> geralmente representa que 100% da variância delas é explicada por si mesmas no contexto de não serem preditas por outras variáveis no modelo, ou simplesmente sua variância total (que é 1 em uma escala padronizada).</li>
<li><code>cyl &lt;-&gt; disp</code>: Correlação de 0.90 (forte, positiva). Carros com mais cilindros tendem a ter maior cilindrada.</li>
<li><code>disp &lt;-&gt; hp</code>: Correlação de 0.83 (forte, positiva). Carros com maior cilindrada tendem a ter maior potência.</li>
<li><code>disp &lt;-&gt; disp</code> (1.00): O mesmo que para <code>cyl</code>.</li>
<li><code>hp &lt;-&gt; hp</code> (1.00): O mesmo.</li>
<li><code>hp &lt;-&gt; wt</code>: Correlação de 0.79 (forte, positiva). Carros com maior potência tendem a ser mais pesados.</li>
<li><code>disp &lt;-&gt; wt</code>: Correlação de 0.78 (forte, positiva). Carros com maior cilindrada tendem a ser mais pesados.</li>
<li><code>wt &lt;-&gt; wt</code> (1.00): O mesmo.</li>
<li><code>cyl &lt;-&gt; hp</code> (não mostrado diretamente, mas inferido através de disp).</li>
<li><code>cyl &lt;-&gt; wt</code> (não mostrado diretamente, mas inferido).</li>
<li><code>hp &lt;-&gt; cyl</code> (0.89): Forte correlação positiva.</li>
<li><code>wt &lt;-&gt; hp</code> (0.66): Correlação positiva.</li>
<li><strong>Em resumo:</strong> Essas quatro variáveis (<code>cyl</code>, <code>disp</code>, <code>hp</code>, <code>wt</code>) são altamente correlacionadas entre si. Isso é esperado, pois elas são características intrínsecas do motor e do carro que geralmente andam juntas.</li>
</ul></li>
</ul>
<p><strong>2. Relações entre Variáveis de Características do Carro e <code>mpg</code> (Consumo):</strong></p>
<ul>
<li><code>cyl -&gt; mpg</code>: Coeficiente de -0.29 (vermelho, fraco a moderado, negativo). Carros com mais cilindros tendem a ter menor <code>mpg</code> (pior consumo de combustível).</li>
<li><code>disp -&gt; mpg</code>: Coeficiente de -0.44 (vermelho, moderado, negativo). Carros com maior cilindrada tendem a ter menor <code>mpg</code>.</li>
<li><code>hp -&gt; mpg</code>: Coeficiente de -0.19 (vermelho, fraco, negativo). Carros com maior potência tendem a ter menor <code>mpg</code>.</li>
<li><code>wt -&gt; mpg</code>: <strong>Não há seta direta de <code>wt</code> para <code>mpg</code> neste modelo.</strong> Isso sugere que o modelo não assume uma relação direta de <code>wt</code> para <code>mpg</code> APÓS contabilizar as outras variáveis, ou a relação não foi estatisticamente significativa para ser incluída ou é indireta.
<ul>
<li><strong>Em resumo:</strong> Cilindros, cilindrada e potência estão negativamente associadas ao consumo de combustível. Carros com características de motor mais “potentes” ou “maiores” tendem a consumir mais combustível (menor <code>mpg</code>). <code>disp</code> tem o efeito direto negativo mais forte em <code>mpg</code>.</li>
</ul></li>
</ul>
<p><strong>3. Relações entre Variáveis de Características do Carro e <code>qsec</code> (Tempo de 1/4 de Milha):</strong></p>
<ul>
<li><code>disp -&gt; qsec</code>: Coeficiente de -0.56 (vermelho, moderado a forte, negativo). Carros com maior cilindrada tendem a ter um tempo de 1/4 de milha menor (ou seja, são mais rápidos).</li>
<li><code>hp -&gt; qsec</code>: Coeficiente de -0.85 (vermelho, muito forte, negativo). Carros com maior potência tendem a ter um tempo de 1/4 de milha significativamente menor (são muito mais rápidos).</li>
<li><code>wt -&gt; qsec</code>: Coeficiente de 0.91 (verde, muito forte, positivo). Carros mais pesados tendem a ter um tempo de 1/4 de milha maior (ou seja, são mais lentos).
<ul>
<li><strong>Em resumo:</strong> Cilindrada e potência contribuem para um carro mais rápido (menor <code>qsec</code>), com a potência (<code>hp</code>) sendo o fator mais influente. O peso (<code>wt</code>), por outro lado, torna o carro mais lento (maior <code>qsec</code>), com uma influência igualmente forte.</li>
</ul></li>
</ul>
<p><strong>4. Relação entre <code>mpg</code> e <code>qsec</code>:</strong></p>
<ul>
<li><code>mpg &lt;-&gt; qsec</code>: Coeficiente de 0.16 (verde, fraco, positivo). Há uma correlação positiva fraca entre <code>mpg</code> e <code>qsec</code>. Carros com melhor consumo de combustível tendem a ter um tempo de 1/4 de milha ligeiramente maior (são um pouco mais lentos). É importante notar que esta é uma <em>correlação</em> bidirecional, não uma relação causal direta no sentido de <code>mpg</code> causando <code>qsec</code> ou vice-versa neste modelo específico. Pode ser que variáveis não modeladas ou efeitos indiretos expliquem essa correlação.</li>
</ul>
<p><strong>5. Variância Residual (Loops nas Variáveis Dependentes):</strong></p>
<ul>
<li><code>mpg &lt;-&gt; mpg</code> (0.23): Este é o coeficiente de variância residual para <code>mpg</code>. Significa que 23% da variância de <code>mpg</code> NÃO é explicada pelas variáveis preditoras (<code>cyl</code>, <code>disp</code>, <code>hp</code>) incluídas no modelo para <code>mpg</code>. Ou, em outras palavras, as variáveis <code>cyl</code>, <code>disp</code>, <code>hp</code> explicam <code>1 - 0.23 = 0.77</code> ou 77% da variância em <code>mpg</code> (o R-quadrado).</li>
<li><code>qsec &lt;-&gt; qsec</code> (0.31): Este é o coeficiente de variância residual para <code>qsec</code>. Significa que 31% da variância de <code>qsec</code> NÃO é explicada pelas variáveis preditoras (<code>disp</code>, <code>hp</code>, <code>wt</code>) incluídas no modelo para <code>qsec</code>. Portanto, <code>disp</code>, <code>hp</code>, <code>wt</code> explicam <code>1 - 0.31 = 0.69</code> ou 69% da variância em <code>qsec</code>.</li>
</ul>
<p><strong>Conclusões Gerais e Interpretação do Modelo:</strong></p>
<p>Este modelo tenta explicar o consumo de combustível (<code>mpg</code>) e o desempenho de 1/4 de milha (<code>qsec</code>) usando características do motor e peso do carro.</p>
<ul>
<li><strong>Consumo de Combustível (<code>mpg</code>):</strong> É predominantemente influenciado negativamente por <code>disp</code> e <code>cyl</code>, e um pouco por <code>hp</code>. Carros com motores maiores/mais potentes tendem a ser menos eficientes em termos de combustível.</li>
<li><strong>Desempenho de 1/4 de Milha (<code>qsec</code>):</strong> É fortemente influenciado pela potência (<code>hp</code>) e peso (<code>wt</code>), e também pela cilindrada (<code>disp</code>). Mais potência e menor cilindrada (para motores mais eficientes) levam a carros mais rápidos, enquanto maior peso torna os carros mais lentos. <code>hp</code> e <code>wt</code> têm os efeitos mais proeminentes.</li>
<li><strong>Correlações Elevadas entre Preditoras:</strong> As altas correlações entre <code>cyl</code>, <code>disp</code>, <code>hp</code>, e <code>wt</code> são um ponto importante. Em modelos de regressão múltipla, isso poderia indicar multicolinearidade. Em SEM, isso é explicitamente modelado pelas covariâncias. Isso significa que essas variáveis não são independentes em seus efeitos, e os efeitos diretos que vemos (<code>cyl -&gt; mpg</code>, <code>disp -&gt; mpg</code>, etc.) são os efeitos <em>após</em> contabilizar a inter-relação entre as preditoras.</li>
<li><strong>Poder Explicativo:</strong> O modelo explica uma grande parte da variância em <code>mpg</code> (77%) e <code>qsec</code> (69%), o que é bastante razoável.</li>
</ul>
<p>Este diagrama oferece uma representação visual clara das relações entre as variáveis, permitindo entender rapidamente quais fatores são mais influentes e em que direção. As setas mais espessas e os coeficientes de maior magnitude (<code>-0.85</code> de <code>hp</code> para <code>qsec</code>, <code>0.91</code> de <code>wt</code> para <code>qsec</code>, <code>0.90</code> de <code>cyl</code> para <code>disp</code>) são os pontos-chave de atenção para as relações mais fortes.</p>
</div>
</div>
</div>
<hr>
<p><strong>Caso2 - Estudo de impacto da satisfação no trabalho sobre a produtividade, mediado pela motivação</strong></p>
<ol type="1">
<li><p>Vamos gerar dados simulados para este modelo.</p></li>
<li><p>Especificar(definir) o modeo SEM. A especificação do modelo SEM é feito com uma string(em formato de texto nota que foi usado aspas ou apóstrofos)</p>
<ul>
<li><p><strong>Definir as variáveis latentes</strong></p>
<ul>
<li><p><code>Satisfação no trabalho</code> (medida por perguntas sobre ambiente, salário, reconhecimento)</p></li>
<li><p><code>Motivação</code> (medida por perguntas sobre engajamento, metas, esforço)</p></li>
<li><p><code>Produtividade</code> (medida por desempenho, entregas, qualidade)</p></li>
</ul></li>
<li><p><strong>Definir as equações estruturais</strong></p>
<ul>
<li><code>Satisfação → Motivação → Produtividade</code></li>
</ul></li>
</ul></li>
<li><p>Rodar o modelo usando o pacote <code>lavaan</code> e mostar os resultados arrumados usando os pacotes <code>broom</code> <span class="citation" data-cites="robinson2025">Robinson, Hayes, and Couch (<a href="#ref-robinson2025" role="doc-biblioref">2025</a>)</span> e <code>gt</code> <span class="citation" data-cites="iannone2025">Iannone et al. (<a href="#ref-iannone2025" role="doc-biblioref">2025</a>)</span></p></li>
</ol>
<div class="cell" data-mmessage="false">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># chamar a package</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># step1: simular os dados</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">300</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>Satisfacao1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean=</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>Satisfacao2 <span class="ot">&lt;-</span> Satisfacao1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>Satisfacao3 <span class="ot">&lt;-</span> Satisfacao1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>Motivacao1 <span class="ot">&lt;-</span> <span class="fl">0.6</span><span class="sc">*</span>Satisfacao1 <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>Motivacao2 <span class="ot">&lt;-</span> Motivacao1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>Motivacao3 <span class="ot">&lt;-</span> Motivacao1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>Produtividade1 <span class="ot">&lt;-</span> <span class="fl">0.7</span><span class="sc">*</span>Motivacao1 <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>Produtividade2 <span class="ot">&lt;-</span> Produtividade1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>Produtividade3 <span class="ot">&lt;-</span> Produtividade1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>dados_produtiv <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Satisfacao1, Satisfacao2, Satisfacao3,</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>                    Motivacao1, Motivacao2, Motivacao3,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>                    Produtividade1, Produtividade2, Produtividade3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Espeficicar o modelo. Note que temos indicadores <code>=~</code> e previsão <code>~</code> na estrutura.</p>
<ul>
<li>Os indicadores <code>Satisfacao1 + Satisfacao2 + Satisfacao3</code> constrem a variável latente <code>Satisfação</code></li>
<li>A Satisfação prevê a <code>Motivação</code> e a <code>Motivação</code> prevê a <code>Produtividade</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step2: especificar o modelo com string(texto)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>mdl_fit_spec_impact_motiv_prod <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="st">  # Variáveis latentes</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="st">  Satisfacao =~ Satisfacao1 + Satisfacao2 + Satisfacao3</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="st">  Motivacao =~ Motivacao1 + Motivacao2 + Motivacao3</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="st">  Produtividade =~ Produtividade1 + Produtividade2 + Produtividade3</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="st">  # Relações estruturais</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="st">  Motivacao ~ Satisfacao</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="st">  Produtividade ~ Motivacao</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Rodar o modelo e mostrar os resultados via <code>summary function</code> e também resultados arrumados usando os pacotes <code>broom</code> e <code>gt</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step3: rodar o modelo e mostrar os resultads</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Rodar o modelo</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>mdl_fit_sem_impact_motiv_prod <span class="ot">&lt;-</span> <span class="fu">sem</span>(mdl_fit_spec_impact_motiv_prod,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">data =</span> dados_produtiv)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar resultados via summary</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl_fit_sem_impact_motiv_prod,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">fit.measures =</span> <span class="cn">TRUE</span>,    </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 43 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        20

  Number of observations                           300

Model Test User Model:
                                                      
  Test statistic                                24.186
  Degrees of freedom                                25
  P-value (Chi-square)                           0.509

Model Test Baseline Model:

  Test statistic                              3557.984
  Degrees of freedom                                36
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    1.000
  Tucker-Lewis Index (TLI)                       1.000

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)              -2549.336
  Loglikelihood unrestricted model (H1)      -2537.243
                                                      
  Akaike (AIC)                                5138.672
  Bayesian (BIC)                              5212.748
  Sample-size adjusted Bayesian (SABIC)       5149.320

Root Mean Square Error of Approximation:

  RMSEA                                          0.000
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.044
  P-value H_0: RMSEA &lt;= 0.050                    0.977
  P-value H_0: RMSEA &gt;= 0.080                    0.000

Standardized Root Mean Square Residual:

  SRMR                                           0.018

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Satisfacao =~                                                         
    Satisfacao1       1.000                               0.943    0.999
    Satisfacao2       0.970    0.034   28.678    0.000    0.915    0.881
    Satisfacao3       0.977    0.035   27.822    0.000    0.922    0.873
  Motivacao =~                                                          
    Motivacao1        1.000                               1.183    1.009
    Motivacao2        0.986    0.025   38.792    0.000    1.166    0.915
    Motivacao3        0.994    0.026   38.198    0.000    1.176    0.913
  Produtividade =~                                                      
    Produtividade1    1.000                               1.296    0.998
    Produtividade2    1.005    0.022   45.593    0.000    1.303    0.943
    Produtividade3    1.018    0.023   43.379    0.000    1.319    0.936

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Motivacao ~                                                           
    Satisfacao        0.629    0.063   10.038    0.000    0.501    0.501
  Produtividade ~                                                       
    Motivacao         0.684    0.049   13.890    0.000    0.624    0.624

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .Satisfacao1       0.002    0.014    0.118    0.906    0.002    0.002
   .Satisfacao2       0.241    0.024   10.155    0.000    0.241    0.224
   .Satisfacao3       0.264    0.025   10.386    0.000    0.264    0.237
   .Motivacao1       -0.025    0.012   -2.076    0.038   -0.025   -0.018
   .Motivacao2        0.263    0.024   10.946    0.000    0.263    0.162
   .Motivacao3        0.276    0.025   11.023    0.000    0.276    0.166
   .Produtividade1    0.006    0.012    0.463    0.643    0.006    0.003
   .Produtividade2    0.213    0.021    9.973    0.000    0.213    0.111
   .Produtividade3    0.245    0.024   10.332    0.000    0.245    0.123
    Satisfacao        0.890    0.074   12.002    0.000    1.000    1.000
   .Motivacao         1.048    0.085   12.375    0.000    0.749    0.749
   .Produtividade     1.025    0.084   12.171    0.000    0.610    0.610</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar resultados arrumados usando broom::tidy() e broom::glance()</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># coeficientes de regressão (loadings)</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mdl_fit_sem_impact_motiv_prod) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(op<span class="sc">==</span><span class="st">"=~"</span>) <span class="sc">%&gt;%</span> gt<span class="sc">::</span><span class="fu">gt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="damqupuxfx" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#damqupuxfx table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#damqupuxfx thead, #damqupuxfx tbody, #damqupuxfx tfoot, #damqupuxfx tr, #damqupuxfx td, #damqupuxfx th {
  border-style: none;
}

#damqupuxfx p {
  margin: 0;
  padding: 0;
}

#damqupuxfx .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#damqupuxfx .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#damqupuxfx .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#damqupuxfx .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#damqupuxfx .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#damqupuxfx .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#damqupuxfx .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#damqupuxfx .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#damqupuxfx .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#damqupuxfx .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#damqupuxfx .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#damqupuxfx .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#damqupuxfx .gt_spanner_row {
  border-bottom-style: hidden;
}

#damqupuxfx .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#damqupuxfx .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#damqupuxfx .gt_from_md > :first-child {
  margin-top: 0;
}

#damqupuxfx .gt_from_md > :last-child {
  margin-bottom: 0;
}

#damqupuxfx .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#damqupuxfx .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#damqupuxfx .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#damqupuxfx .gt_row_group_first td {
  border-top-width: 2px;
}

#damqupuxfx .gt_row_group_first th {
  border-top-width: 2px;
}

#damqupuxfx .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#damqupuxfx .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#damqupuxfx .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#damqupuxfx .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#damqupuxfx .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#damqupuxfx .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#damqupuxfx .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#damqupuxfx .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#damqupuxfx .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#damqupuxfx .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#damqupuxfx .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#damqupuxfx .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#damqupuxfx .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#damqupuxfx .gt_left {
  text-align: left;
}

#damqupuxfx .gt_center {
  text-align: center;
}

#damqupuxfx .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#damqupuxfx .gt_font_normal {
  font-weight: normal;
}

#damqupuxfx .gt_font_bold {
  font-weight: bold;
}

#damqupuxfx .gt_font_italic {
  font-style: italic;
}

#damqupuxfx .gt_super {
  font-size: 65%;
}

#damqupuxfx .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#damqupuxfx .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#damqupuxfx .gt_indent_1 {
  text-indent: 5px;
}

#damqupuxfx .gt_indent_2 {
  text-indent: 10px;
}

#damqupuxfx .gt_indent_3 {
  text-indent: 15px;
}

#damqupuxfx .gt_indent_4 {
  text-indent: 20px;
}

#damqupuxfx .gt_indent_5 {
  text-indent: 25px;
}

#damqupuxfx .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#damqupuxfx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="term" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">term</th>
<th id="op" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">op</th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">estimate</th>
<th id="std.error" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">std.error</th>
<th id="statistic" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">statistic</th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">p.value</th>
<th id="std.lv" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">std.lv</th>
<th id="std.all" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">std.all</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="term">Satisfacao =~ Satisfacao1</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0000000</td>
<td class="gt_row gt_right" headers="std.error">0.00000000</td>
<td class="gt_row gt_right" headers="statistic">NA</td>
<td class="gt_row gt_right" headers="p.value">NA</td>
<td class="gt_row gt_right" headers="std.lv">0.9433211</td>
<td class="gt_row gt_right" headers="std.all">0.9990669</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">Satisfacao =~ Satisfacao2</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">0.9700618</td>
<td class="gt_row gt_right" headers="std.error">0.03382592</td>
<td class="gt_row gt_right" headers="statistic">28.67806</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">0.9150797</td>
<td class="gt_row gt_right" headers="std.all">0.8811103</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">Satisfacao =~ Satisfacao3</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">0.9770718</td>
<td class="gt_row gt_right" headers="std.error">0.03511884</td>
<td class="gt_row gt_right" headers="statistic">27.82187</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">0.9216924</td>
<td class="gt_row gt_right" headers="std.all">0.8734059</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">Motivacao =~ Motivacao1</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0000000</td>
<td class="gt_row gt_right" headers="std.error">0.00000000</td>
<td class="gt_row gt_right" headers="statistic">NA</td>
<td class="gt_row gt_right" headers="p.value">NA</td>
<td class="gt_row gt_right" headers="std.lv">1.1831000</td>
<td class="gt_row gt_right" headers="std.all">1.0089639</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">Motivacao =~ Motivacao2</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">0.9858050</td>
<td class="gt_row gt_right" headers="std.error">0.02541238</td>
<td class="gt_row gt_right" headers="statistic">38.79230</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.1663058</td>
<td class="gt_row gt_right" headers="std.all">0.9153346</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">Motivacao =~ Motivacao3</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">0.9940990</td>
<td class="gt_row gt_right" headers="std.error">0.02602470</td>
<td class="gt_row gt_right" headers="statistic">38.19828</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.1761185</td>
<td class="gt_row gt_right" headers="std.all">0.9129636</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">Produtividade =~ Produtividade1</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0000000</td>
<td class="gt_row gt_right" headers="std.error">0.00000000</td>
<td class="gt_row gt_right" headers="statistic">NA</td>
<td class="gt_row gt_right" headers="p.value">NA</td>
<td class="gt_row gt_right" headers="std.lv">1.2963707</td>
<td class="gt_row gt_right" headers="std.all">0.9983183</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">Produtividade =~ Produtividade2</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0050916</td>
<td class="gt_row gt_right" headers="std.error">0.02204492</td>
<td class="gt_row gt_right" headers="statistic">45.59289</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.3029712</td>
<td class="gt_row gt_right" headers="std.all">0.9426245</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">Produtividade =~ Produtividade3</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0178094</td>
<td class="gt_row gt_right" headers="std.error">0.02346338</td>
<td class="gt_row gt_right" headers="statistic">43.37864</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.3194583</td>
<td class="gt_row gt_right" headers="std.all">0.9363450</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># principais medidas de ajuste</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(mdl_fit_sem_impact_motiv_prod) <span class="sc">%&gt;%</span> gt<span class="sc">::</span><span class="fu">gt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="ggvuytnoep" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ggvuytnoep table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ggvuytnoep thead, #ggvuytnoep tbody, #ggvuytnoep tfoot, #ggvuytnoep tr, #ggvuytnoep td, #ggvuytnoep th {
  border-style: none;
}

#ggvuytnoep p {
  margin: 0;
  padding: 0;
}

#ggvuytnoep .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ggvuytnoep .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ggvuytnoep .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ggvuytnoep .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ggvuytnoep .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ggvuytnoep .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ggvuytnoep .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ggvuytnoep .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ggvuytnoep .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ggvuytnoep .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ggvuytnoep .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ggvuytnoep .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ggvuytnoep .gt_spanner_row {
  border-bottom-style: hidden;
}

#ggvuytnoep .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ggvuytnoep .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ggvuytnoep .gt_from_md > :first-child {
  margin-top: 0;
}

#ggvuytnoep .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ggvuytnoep .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ggvuytnoep .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ggvuytnoep .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ggvuytnoep .gt_row_group_first td {
  border-top-width: 2px;
}

#ggvuytnoep .gt_row_group_first th {
  border-top-width: 2px;
}

#ggvuytnoep .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ggvuytnoep .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ggvuytnoep .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ggvuytnoep .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ggvuytnoep .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ggvuytnoep .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ggvuytnoep .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ggvuytnoep .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ggvuytnoep .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ggvuytnoep .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ggvuytnoep .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ggvuytnoep .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ggvuytnoep .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ggvuytnoep .gt_left {
  text-align: left;
}

#ggvuytnoep .gt_center {
  text-align: center;
}

#ggvuytnoep .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ggvuytnoep .gt_font_normal {
  font-weight: normal;
}

#ggvuytnoep .gt_font_bold {
  font-weight: bold;
}

#ggvuytnoep .gt_font_italic {
  font-style: italic;
}

#ggvuytnoep .gt_super {
  font-size: 65%;
}

#ggvuytnoep .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ggvuytnoep .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ggvuytnoep .gt_indent_1 {
  text-indent: 5px;
}

#ggvuytnoep .gt_indent_2 {
  text-indent: 10px;
}

#ggvuytnoep .gt_indent_3 {
  text-indent: 15px;
}

#ggvuytnoep .gt_indent_4 {
  text-indent: 20px;
}

#ggvuytnoep .gt_indent_5 {
  text-indent: 25px;
}

#ggvuytnoep .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#ggvuytnoep div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="agfi" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">agfi</th>
<th id="AIC" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">AIC</th>
<th id="BIC" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">BIC</th>
<th id="cfi" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">cfi</th>
<th id="chisq" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">chisq</th>
<th id="npar" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">npar</th>
<th id="rmsea" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">rmsea</th>
<th id="rmsea.conf.high" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">rmsea.conf.high</th>
<th id="srmr" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">srmr</th>
<th id="tli" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">tli</th>
<th id="converged" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">converged</th>
<th id="estimator" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">estimator</th>
<th id="ngroups" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">ngroups</th>
<th id="missing_method" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">missing_method</th>
<th id="nobs" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">nobs</th>
<th id="norig" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">norig</th>
<th id="nexcluded" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">nexcluded</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="agfi">0.9693424</td>
<td class="gt_row gt_right" headers="AIC">5138.672</td>
<td class="gt_row gt_right" headers="BIC">5212.748</td>
<td class="gt_row gt_right" headers="cfi">1</td>
<td class="gt_row gt_right" headers="chisq">24.18603</td>
<td class="gt_row gt_right" headers="npar">20</td>
<td class="gt_row gt_right" headers="rmsea">0</td>
<td class="gt_row gt_right" headers="rmsea.conf.high">0.04444163</td>
<td class="gt_row gt_right" headers="srmr">0.01832338</td>
<td class="gt_row gt_right" headers="tli">1.000333</td>
<td class="gt_row gt_center" headers="converged">TRUE</td>
<td class="gt_row gt_left" headers="estimator">ML</td>
<td class="gt_row gt_right" headers="ngroups">1</td>
<td class="gt_row gt_left" headers="missing_method">listwise</td>
<td class="gt_row gt_right" headers="nobs">300</td>
<td class="gt_row gt_right" headers="norig">300</td>
<td class="gt_row gt_right" headers="nexcluded">0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Resultados</strong></p>
<ul>
<li>Cargas fatoriais mostrando como cada indicador representa sua variável latente.</li>
<li>Coeficientes padronizados das relações entre Satisfacao, Motivacao e Produtividade.</li>
<li>Índices de ajuste como RMSEA, CFI, TLI para avaliar a qualidade do modelo.</li>
</ul>
<hr>
<p><strong>Caso3 - Exemplo em manufatura onde queremos entender por que uma linha de montagem está com baixa produtividade. Suspeitamos que isso tem a ver com treinamento de operadores, qualidade das matérias primas e clima organizacional</strong></p>
<p>Esses fatores não afetam diretamente a produtividade, mas influenciam a motivação e eficiência operacional, que por sua vez afetam a produtividade.</p>
<ol type="1">
<li><p>Vamos simular uma fábrica com as variáveis <code>treinamento</code>, <code>qualidade materia prima</code>, <code>clima organizacional</code>, <code>motivação</code>, <code>eficiência operacional</code> e <code>produtividade</code> e gerar um gráfico de correlações.</p></li>
<li><p>Vamos definir o modelo <code>SEM</code> com relações causais entre essa variáveis.</p></li>
<li><p>Ajustar o modelo e gerar um resumo com cargas fatoriais, coeficientes padronizados, índices de ajustes(e.g.&nbsp;CFI, RMSEA, etc)</p></li>
<li><p>Implementar o modelo no R</p></li>
<li><p>Mostrar os resultados no diagrama</p></li>
</ol>
<p>Gerar os dados de produtividade e plotar as correlações usando corrr package <span class="citation" data-cites="kuhn2022">Kuhn, Jackson, and Cimentada (<a href="#ref-kuhn2022" role="doc-biblioref">2022</a>)</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># carregar package</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrr)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># step1: simular dados de manufatura e gerar correlações</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">300</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># indicadores de variáveis latentes</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>treinamento_1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean=</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>treinamento_2 <span class="ot">&lt;-</span> treinamento_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>treinamento_3 <span class="ot">&lt;-</span> treinamento_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>qualy_material_1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean=</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>qualy_material_2 <span class="ot">&lt;-</span> qualy_material_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>qualy_material_3 <span class="ot">&lt;-</span> qualy_material_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>clima_org_1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean=</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>clima_org_2 <span class="ot">&lt;-</span> clima_org_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>clima_org_3 <span class="ot">&lt;-</span> clima_org_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>motivacao_1 <span class="ot">&lt;-</span> <span class="fl">0.6</span><span class="sc">*</span>treinamento_1 <span class="sc">+</span> <span class="fl">0.4</span><span class="sc">*</span>clima_org_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>motivacao_2 <span class="ot">&lt;-</span> motivacao_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>motivacao_3 <span class="ot">&lt;-</span> motivacao_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>eficiencia_oper_1 <span class="ot">&lt;-</span> <span class="fl">0.5</span><span class="sc">*</span>qualy_material_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>eficiencia_oper_2 <span class="ot">&lt;-</span> eficiencia_oper_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>eficiencia_oper_3 <span class="ot">&lt;-</span> eficiencia_oper_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>produtividade_1 <span class="ot">&lt;-</span> <span class="fl">0.6</span><span class="sc">*</span>motivacao_1 <span class="sc">+</span> <span class="fl">0.5</span><span class="sc">*</span>eficiencia_oper_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>produtividade_2 <span class="ot">&lt;-</span> produtividade_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>produtividade_3 <span class="ot">&lt;-</span> produtividade_1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a><span class="co"># jogar dentro do dataframe</span></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>data_produtividade <span class="ot">&lt;-</span> </span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(treinamento_1, treinamento_2, treinamento_3,</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>         qualy_material_1, qualy_material_2, qualy_material_3,</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>         clima_org_1, clima_org_2, clima_org_3,</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>         motivacao_1, motivacao_2, motivacao_3,</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>         eficiencia_oper_1, eficiencia_oper_2, eficiencia_oper_3,</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>         produtividade_1, produtividade_2, produtividade_3)</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a><span class="co"># gerar correlações</span></span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>data_produtividade <span class="sc">%&gt;%</span> </span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shave</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rplot</span>(<span class="at">print_cor =</span> <span class="cn">TRUE</span>)<span class="sc">+</span></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">label =</span> abbreviate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="modelagem_equacoes_estruturais_files/figure-html/data_produtividade-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Criar a especificação do modelo. Note que neste exemplo temos variáveis <code>latentes</code> e usaremos as sintaxes para indicador <code>=~</code> e sintaxe para previsão <code>~</code>.</p>
<p>Rodar o modelo e mostrar os resultados arrumados em formato de tabela.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># step2: especificar modelo SEM</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>mdl_spec_produtividade <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="st">  # variaveis latentes</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="st">  treinamento =~ treinamento_1 + treinamento_2 + treinamento_3</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="st">  qualidade_material =~ qualy_material_1 + qualy_material_2 + qualy_material_3</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="st">  clima_org =~ clima_org_1 + clima_org_2 + clima_org_3</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="st">  motivacao =~ motivacao_1 + motivacao_2 + motivacao_3</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="st">  eficiencia_oper =~ eficiencia_oper_1 + eficiencia_oper_2 + eficiencia_oper_3</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="st">  produtividade =~ produtividade_1 + produtividade_2 + produtividade_3</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="st">  # Structural relationships</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="st">  motivacao ~ treinamento + clima_org</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="st">  eficiencia_oper ~ qualidade_material</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="st">  produtividade ~ motivacao + eficiencia_oper</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co"># step3: rodar o modelo</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>mdl_fit_produtividade <span class="ot">&lt;-</span> <span class="fu">sem</span>(mdl_spec_produtividade, </span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>                             <span class="at">data =</span> data_produtividade)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="co"># step4: mostrar o resumo arrumado com broom::tidy()</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mdl_fit_produtividade) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(op <span class="sc">==</span> <span class="st">"=~"</span>) <span class="sc">%&gt;%</span> gt<span class="sc">::</span><span class="fu">gt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="zejjhmhcgm" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#zejjhmhcgm table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#zejjhmhcgm thead, #zejjhmhcgm tbody, #zejjhmhcgm tfoot, #zejjhmhcgm tr, #zejjhmhcgm td, #zejjhmhcgm th {
  border-style: none;
}

#zejjhmhcgm p {
  margin: 0;
  padding: 0;
}

#zejjhmhcgm .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zejjhmhcgm .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#zejjhmhcgm .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zejjhmhcgm .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zejjhmhcgm .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zejjhmhcgm .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zejjhmhcgm .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zejjhmhcgm .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zejjhmhcgm .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zejjhmhcgm .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zejjhmhcgm .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zejjhmhcgm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zejjhmhcgm .gt_spanner_row {
  border-bottom-style: hidden;
}

#zejjhmhcgm .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#zejjhmhcgm .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zejjhmhcgm .gt_from_md > :first-child {
  margin-top: 0;
}

#zejjhmhcgm .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zejjhmhcgm .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zejjhmhcgm .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#zejjhmhcgm .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#zejjhmhcgm .gt_row_group_first td {
  border-top-width: 2px;
}

#zejjhmhcgm .gt_row_group_first th {
  border-top-width: 2px;
}

#zejjhmhcgm .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zejjhmhcgm .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#zejjhmhcgm .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#zejjhmhcgm .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zejjhmhcgm .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zejjhmhcgm .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zejjhmhcgm .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#zejjhmhcgm .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zejjhmhcgm .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zejjhmhcgm .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zejjhmhcgm .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zejjhmhcgm .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zejjhmhcgm .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zejjhmhcgm .gt_left {
  text-align: left;
}

#zejjhmhcgm .gt_center {
  text-align: center;
}

#zejjhmhcgm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zejjhmhcgm .gt_font_normal {
  font-weight: normal;
}

#zejjhmhcgm .gt_font_bold {
  font-weight: bold;
}

#zejjhmhcgm .gt_font_italic {
  font-style: italic;
}

#zejjhmhcgm .gt_super {
  font-size: 65%;
}

#zejjhmhcgm .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#zejjhmhcgm .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#zejjhmhcgm .gt_indent_1 {
  text-indent: 5px;
}

#zejjhmhcgm .gt_indent_2 {
  text-indent: 10px;
}

#zejjhmhcgm .gt_indent_3 {
  text-indent: 15px;
}

#zejjhmhcgm .gt_indent_4 {
  text-indent: 20px;
}

#zejjhmhcgm .gt_indent_5 {
  text-indent: 25px;
}

#zejjhmhcgm .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#zejjhmhcgm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="term" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">term</th>
<th id="op" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">op</th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">estimate</th>
<th id="std.error" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">std.error</th>
<th id="statistic" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">statistic</th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">p.value</th>
<th id="std.lv" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">std.lv</th>
<th id="std.all" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">std.all</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="term">treinamento =~ treinamento_1</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0000000</td>
<td class="gt_row gt_right" headers="std.error">0.00000000</td>
<td class="gt_row gt_right" headers="statistic">NA</td>
<td class="gt_row gt_right" headers="p.value">NA</td>
<td class="gt_row gt_right" headers="std.lv">0.9536695</td>
<td class="gt_row gt_right" headers="std.all">1.0100266</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">treinamento =~ treinamento_2</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">0.9487177</td>
<td class="gt_row gt_right" headers="std.error">0.03368857</td>
<td class="gt_row gt_right" headers="statistic">28.16141</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">0.9047631</td>
<td class="gt_row gt_right" headers="std.all">0.8711767</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">treinamento =~ treinamento_3</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">0.9560553</td>
<td class="gt_row gt_right" headers="std.error">0.03493380</td>
<td class="gt_row gt_right" headers="statistic">27.36763</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">0.9117607</td>
<td class="gt_row gt_right" headers="std.all">0.8639942</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">qualidade_material =~ qualy_material_1</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0000000</td>
<td class="gt_row gt_right" headers="std.error">0.00000000</td>
<td class="gt_row gt_right" headers="statistic">NA</td>
<td class="gt_row gt_right" headers="p.value">NA</td>
<td class="gt_row gt_right" headers="std.lv">1.0261713</td>
<td class="gt_row gt_right" headers="std.all">1.0085200</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">qualidade_material =~ qualy_material_2</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0203059</td>
<td class="gt_row gt_right" headers="std.error">0.03015008</td>
<td class="gt_row gt_right" headers="statistic">33.84090</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.0470086</td>
<td class="gt_row gt_right" headers="std.all">0.9010183</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">qualidade_material =~ qualy_material_3</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0206101</td>
<td class="gt_row gt_right" headers="std.error">0.03095638</td>
<td class="gt_row gt_right" headers="statistic">32.96930</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.0473208</td>
<td class="gt_row gt_right" headers="std.all">0.8959953</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">clima_org =~ clima_org_1</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0000000</td>
<td class="gt_row gt_right" headers="std.error">0.00000000</td>
<td class="gt_row gt_right" headers="statistic">NA</td>
<td class="gt_row gt_right" headers="p.value">NA</td>
<td class="gt_row gt_right" headers="std.lv">1.0079050</td>
<td class="gt_row gt_right" headers="std.all">0.9996121</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">clima_org =~ clima_org_2</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">0.9822390</td>
<td class="gt_row gt_right" headers="std.error">0.02947692</td>
<td class="gt_row gt_right" headers="statistic">33.32231</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">0.9900036</td>
<td class="gt_row gt_right" headers="std.all">0.9045366</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">clima_org =~ clima_org_3</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0363995</td>
<td class="gt_row gt_right" headers="std.error">0.03141992</td>
<td class="gt_row gt_right" headers="statistic">32.98543</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.0445922</td>
<td class="gt_row gt_right" headers="std.all">0.9024897</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">motivacao =~ motivacao_1</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0000000</td>
<td class="gt_row gt_right" headers="std.error">0.00000000</td>
<td class="gt_row gt_right" headers="statistic">NA</td>
<td class="gt_row gt_right" headers="p.value">NA</td>
<td class="gt_row gt_right" headers="std.lv">1.2626775</td>
<td class="gt_row gt_right" headers="std.all">1.0004987</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">motivacao =~ motivacao_2</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">0.9902022</td>
<td class="gt_row gt_right" headers="std.error">0.02433893</td>
<td class="gt_row gt_right" headers="statistic">40.68388</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.2503061</td>
<td class="gt_row gt_right" headers="std.all">0.9266683</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">motivacao =~ motivacao_3</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0356239</td>
<td class="gt_row gt_right" headers="std.error">0.02391868</td>
<td class="gt_row gt_right" headers="statistic">43.29770</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.3076590</td>
<td class="gt_row gt_right" headers="std.all">0.9352251</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">eficiencia_oper =~ eficiencia_oper_1</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0000000</td>
<td class="gt_row gt_right" headers="std.error">0.00000000</td>
<td class="gt_row gt_right" headers="statistic">NA</td>
<td class="gt_row gt_right" headers="p.value">NA</td>
<td class="gt_row gt_right" headers="std.lv">1.0083403</td>
<td class="gt_row gt_right" headers="std.all">0.9883142</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">eficiencia_oper =~ eficiencia_oper_2</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0547239</td>
<td class="gt_row gt_right" headers="std.error">0.03161671</td>
<td class="gt_row gt_right" headers="statistic">33.35970</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.0635206</td>
<td class="gt_row gt_right" headers="std.all">0.9130939</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">eficiencia_oper =~ eficiencia_oper_3</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">0.9829011</td>
<td class="gt_row gt_right" headers="std.error">0.03181453</td>
<td class="gt_row gt_right" headers="statistic">30.89472</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">0.9910987</td>
<td class="gt_row gt_right" headers="std.all">0.8962644</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">produtividade =~ produtividade_1</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0000000</td>
<td class="gt_row gt_right" headers="std.error">0.00000000</td>
<td class="gt_row gt_right" headers="statistic">NA</td>
<td class="gt_row gt_right" headers="p.value">NA</td>
<td class="gt_row gt_right" headers="std.lv">1.2737279</td>
<td class="gt_row gt_right" headers="std.all">0.9926720</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">produtividade =~ produtividade_2</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0453819</td>
<td class="gt_row gt_right" headers="std.error">0.02332536</td>
<td class="gt_row gt_right" headers="statistic">44.81740</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.3315320</td>
<td class="gt_row gt_right" headers="std.all">0.9447195</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">produtividade =~ produtividade_3</td>
<td class="gt_row gt_left" headers="op">=~</td>
<td class="gt_row gt_right" headers="estimate">1.0149790</td>
<td class="gt_row gt_right" headers="std.error">0.02252503</td>
<td class="gt_row gt_right" headers="statistic">45.06005</td>
<td class="gt_row gt_right" headers="p.value">0</td>
<td class="gt_row gt_right" headers="std.lv">1.2928071</td>
<td class="gt_row gt_right" headers="std.all">0.9454039</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Plotar os resultados no diagrama usando <code>semPlot</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># step5: gerar o diagrama com os resultados.</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>semPlot<span class="sc">::</span><span class="fu">semPaths</span>(mdl_fit_produtividade,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">rotation =</span> <span class="dv">2</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">what =</span> <span class="st">"std"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">layout =</span> <span class="st">"tree"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sizeMan =</span> <span class="dv">8</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sizeLat =</span> <span class="dv">10</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">nCharNodes =</span> <span class="dv">11</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>                  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="modelagem_equacoes_estruturais_files/figure-html/plot_produtividade-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Caso4 - Estudar os efeitos da formação acadêmica no desempenho dos alunos</strong></p>
<p>Este exemplo será feito com o conjunto de dados apresentado por Johnny Lin no seminário <span class="citation" data-cites="uclaofficeofadvancedresearchcomputing2021">UCLA Office of Advanced Research Computing (<a href="#ref-uclaofficeofadvancedresearchcomputing2021" role="doc-biblioref">2021</a>)</span></p>
<p>Imagine que você é um pesquisador investigando os impactos da formação acadêmica dos estudantes no seu desempenho escolar. O laboratório coletou os dados de 500 alunos com 9 variáveis observadas sendo <code>motivação(motiv)</code>, <code>harmonia(harm)</code>, <code>estabilidade(stabi)</code>, <code>psicologia parental negativa(ppsych)</code>, <code>nível sócio econômico(ses)</code>, <code>qi verbal(verbal)</code>, <code>leitura(read)</code>, <code>aritmética(arith)</code> e <code>ortografia(spell)</code>. É formulada a hipótese acerca de três construtos latentes sendo <code>ajuste</code>, <code>risco</code>, <code>conquista</code>, os quais são avaliados conforme o seguinte mapeamento de livro de códigos:</p>
<table class="caption-top table">
<caption>Tabela de medidas</caption>
<thead>
<tr class="header">
<th>Adjust (Ajuste)</th>
<th>Risk (Risco)</th>
<th>Achieve (Conquista)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>motiv</td>
<td>ppsych</td>
<td>read</td>
</tr>
<tr class="even">
<td>harm</td>
<td>ses</td>
<td>arith</td>
</tr>
<tr class="odd">
<td>stabi</td>
<td>verbal</td>
<td>spell</td>
</tr>
</tbody>
</table>
<p>No diagrama abaixo duas variáveis latentes exógenas <code>risk</code> e <code>ajust</code> são estimadas a partir dos indicadores observáveis <code>ses</code>, <code>ppsych</code>, <code>verbal</code>, <code>stabil</code>,<code>harm</code>, <code>motiv</code>. Em seguida, são analisados as relações estruturais com uma variável latente endógena <code>achieve</code> que é estimada pelos indicadores <code>spell</code>, <code>arith</code> e <code>read</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sem_estrutural.png" class="img-fluid figure-img"></p>
<figcaption>Exemplo do diagrama do modelo SEM</figcaption>
</figure>
</div>
<ol type="1">
<li><p>Vamos importar os dados e gerar as correlações</p></li>
<li><p>Definir o modelo <code>SEM</code> com relações causais entre as variáveis.</p></li>
<li><p>Ajustar o modelo e gerar um resumo com cargas fatoriais, coeficientes padronizados, índices de ajustes(e.g.&nbsp;CFI, RMSEA, etc)</p></li>
<li><p>Mostrar os resultados no diagrama</p></li>
</ol>
<p>Importando os dados e gerando as correlações.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># carregar as packages</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrr)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># step1: importar dados e gerar correlacoes</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># importar os dados</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>data_stud <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://stats.idre.ucla.edu/wp-content/uploads/2021/02/worland5.csv"</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># plotar as correlações</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>data_stud <span class="sc">%&gt;%</span> </span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  corrr<span class="sc">::</span><span class="fu">correlate</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  corrr<span class="sc">::</span><span class="fu">rearrange</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  corrr<span class="sc">::</span><span class="fu">shave</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  corrr<span class="sc">::</span><span class="fu">rplot</span>(<span class="at">print_cor =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="modelagem_equacoes_estruturais_files/figure-html/data_students-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Definir o modelo <code>SEM</code> com relações causais entre essa variáveis.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step2: especificar o modelo SEM</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mdl_spec_sem_full <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="st"># modelo de medição</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="st">adjust =~ motiv + harm + stabi</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="st">risk =~ verbal + ppsych + ses</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="st">achieve =~ read + arith + spell</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="st"># modelo estruturante (regression path)</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="st">achieve ~ adjust + risk</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Rodar o modelo e gerar um resumo com cargas fatoriais, coeficientes padronizados, índices de ajustes(e.g.&nbsp;CFI, RMSEA, etc)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step3: rodar o modelo e mostrar resultados</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># rodar modelo</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>mdl_fit_sem_full <span class="ot">&lt;-</span> <span class="fu">sem</span>(mdl_spec_sem_full, <span class="at">data =</span> data_stud)  </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># mostrar resultados com coeficientes padronizados</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdl_fit_sem_full, </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">standardize =</span> <span class="cn">TRUE</span>, </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">fit.measures =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 130 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        21

  Number of observations                           500

Model Test User Model:
                                                      
  Test statistic                               148.982
  Degrees of freedom                                24
  P-value (Chi-square)                           0.000

Model Test Baseline Model:

  Test statistic                              2597.972
  Degrees of freedom                                36
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.951
  Tucker-Lewis Index (TLI)                       0.927

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -15517.857
  Loglikelihood unrestricted model (H1)     -15443.366
                                                      
  Akaike (AIC)                               31077.713
  Bayesian (BIC)                             31166.220
  Sample-size adjusted Bayesian (SABIC)      31099.565

Root Mean Square Error of Approximation:

  RMSEA                                          0.102
  90 Percent confidence interval - lower         0.087
  90 Percent confidence interval - upper         0.118
  P-value H_0: RMSEA &lt;= 0.050                    0.000
  P-value H_0: RMSEA &gt;= 0.080                    0.990

Standardized Root Mean Square Residual:

  SRMR                                           0.041

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  adjust =~                                                             
    motiv             1.000                               9.324    0.933
    harm              0.884    0.041   21.774    0.000    8.246    0.825
    stabi             0.695    0.043   15.987    0.000    6.478    0.648
  risk =~                                                               
    verbal            1.000                               7.319    0.733
    ppsych           -0.770    0.075  -10.223    0.000   -5.636   -0.564
    ses               0.807    0.076   10.607    0.000    5.906    0.591
  achieve =~                                                            
    read              1.000                               9.404    0.941
    arith             0.837    0.034   24.437    0.000    7.873    0.788
    spell             0.976    0.028   34.338    0.000    9.178    0.919

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  achieve ~                                                             
    adjust            0.375    0.046    8.085    0.000    0.372    0.372
    risk              0.724    0.078    9.253    0.000    0.564    0.564

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  adjust ~~                                                             
    risk             32.098    4.320    7.431    0.000    0.470    0.470

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .motiv            12.870    2.852    4.512    0.000   12.870    0.129
   .harm             31.805    2.973   10.698    0.000   31.805    0.319
   .stabi            57.836    3.990   14.494    0.000   57.836    0.580
   .verbal           46.239    4.788    9.658    0.000   46.239    0.463
   .ppsych           68.033    5.068   13.425    0.000   68.033    0.682
   .ses              64.916    4.975   13.048    0.000   64.916    0.650
   .read             11.372    1.608    7.074    0.000   11.372    0.114
   .arith            37.818    2.680   14.109    0.000   37.818    0.379
   .spell            15.560    1.699    9.160    0.000   15.560    0.156
    adjust           86.930    6.830   12.727    0.000    1.000    1.000
    risk             53.561    6.757    7.927    0.000    1.000    1.000
   .achieve          30.685    3.449    8.896    0.000    0.347    0.347</code></pre>
</div>
</div>
<p>Mostrar os resultados no diagrama</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(mdl_fit_sem_full,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>         <span class="st">"std"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">rotation =</span> <span class="dv">2</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="modelagem_equacoes_estruturais_files/figure-html/plot_students-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="pra-onde-vai" class="level3">
<h3 class="anchored" data-anchor-id="pra-onde-vai"><i class="fa-solid fa-5" aria-label="5"></i> <span style="color: #5AC8BE ;"><strong>Pra onde vai?</strong></span></h3>
<p>Depois de construir e validar o modelo SEM, ele pode ser usado para:</p>
<ul>
<li>Tomada de decisão baseada em evidências como priorizar ações de melhoria com base em dados(e.g investir mais em treinamento se ele tiver alto impacto na produtividade, melhorar políticas de RH).</li>
<li>Apoiar decisões estratégias com evidências estatísticas.</li>
<li>Comunicar resultados de forma clara para diretoria e equipes operacionais.</li>
<li>Integrar SEM com sistemas de qualidade e melhoria contínua(e.g Six Sigma, Lean, TPM)</li>
<li>Publicações científicas que testam teorias complexas.</li>
<li>Desenvolvimento de produtos ou serviços com base em fatores que influenciam comportamento do consumidor.</li>
<li>Avaliação de programas sociais ou educacionais.</li>
</ul>
</section>
<section id="qual-resultado" class="level3">
<h3 class="anchored" data-anchor-id="qual-resultado"><i class="fa-solid fa-6" aria-label="6"></i> <span style="color: #5AC8BE ;"><strong>Qual resultado?</strong></span></h3>
<ul>
<li>Mapeamento claro das causas reais de problemas ou oportunidades.</li>
<li>Modelos visuais e estatísticos que mostram como tudo está conectado.</li>
<li>Redução de desperdícios ao focar em ações que realmente fazem a diferença.</li>
<li>Maior confiança nas decisões pois são baseadas em dados e não apenas em experiência ou opinião.</li>
<li>Modelos estatísticos robustos que explicam bem os dados.</li>
<li>Coeficientes padronizados que mostram a força das relações entre variáveis.</li>
<li>Índices de ajuste (como RMSEA, CFI, TLI) que indicam se o modelo representa bem a realidade.</li>
<li>Insights teóricos e práticos sobre os fatores que influenciam fenômenos complexos.</li>
</ul>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-epskamp2025" class="csl-entry" role="listitem">
Epskamp, Sacha. 2025. <em>SachaEpskamp/semPlot</em>. <a href="https://github.com/SachaEpskamp/semPlot">https://github.com/SachaEpskamp/semPlot</a>.
</div>
<div id="ref-iannone2025" class="csl-entry" role="listitem">
Iannone, Richard, Joe Cheng, Barret Schloerke, Ellis Hughes, Alexandra Lauer, JooYoung Seo, Brevoort Ken, and Roy Olivier. 2025. <em>Gt: Easily Create Presentation-Ready Display Tables</em>. <a href="https://github.com/rstudio/gt">https://github.com/rstudio/gt</a>.
</div>
<div id="ref-kuhn2022" class="csl-entry" role="listitem">
Kuhn, Max, Simon Jackson, and Jorge Cimentada. 2022. <em>Tidymodels/Corrr</em>. tidymodels. <a href="https://github.com/tidymodels/corrr">https://github.com/tidymodels/corrr</a>.
</div>
<div id="ref-prof.diogeness.bido2021" class="csl-entry" role="listitem">
Prof. Diogenes S. BIDO. 2021. <span>“Como Medir o Que Não Dá Para Medir? (Conceitos Abstratos Como Variáveis Latentes),”</span> May. <a href="https://www.youtube.com/watch?v=dQrNEIFYmDs">https://www.youtube.com/watch?v=dQrNEIFYmDs</a>.
</div>
<div id="ref-quarto2025" class="csl-entry" role="listitem">
<span>“Quarto.”</span> 2025. <a href="https://quarto.org/">https://quarto.org/</a>.
</div>
<div id="ref-robinson2025" class="csl-entry" role="listitem">
Robinson, David, Alex Hayes, and Simon Couch. 2025. <em>Tidymodels/Broom</em>. tidymodels. <a href="https://github.com/tidymodels/broom">https://github.com/tidymodels/broom</a>.
</div>
<div id="ref-rosseel2024" class="csl-entry" role="listitem">
Rosseel, Yves. 2024. <em>Cran/Lavaan</em>. cran. <a href="https://github.com/cran/lavaan">https://github.com/cran/lavaan</a>.
</div>
<div id="ref-rstudio/2025" class="csl-entry" role="listitem">
<em>Rstudio/Rstudio</em>. 2025. RStudio. <a href="https://github.com/rstudio/rstudio">https://github.com/rstudio/rstudio</a>.
</div>
<div id="ref-uclaofficeofadvancedresearchcomputing2021" class="csl-entry" role="listitem">
UCLA Office of Advanced Research Computing. 2021. <span>“Introduction to Structural Equation Modeling (SEM) in r with Lavaan.”</span> <a href="https://stats.oarc.ucla.edu/r/seminars/rsem/">https://stats.oarc.ucla.edu/r/seminars/rsem/</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/carvalhoribeiro\.netlify\.app\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="factorialmap/blog_comments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->




</body></html>